packages/evolution-common/src/services/interviews/interview.ts
The section status can be available for each section and sections may have subsections.
=> responses: Extract a section status type for the _sections

packages/evolution-legacy/src/components/survey/Section.js
Fixes #81
For normal surveys, the question is simply missing, with a log message containing the name of the missing widget.
If the survey is in dev mode, a red `div` shows the missing widget where it should have been on the page.
=> survey: Log missing widgets instead of blank page

packages/evolution-backend/src/models/migrations/20230509100000_updateInterviewIndexes.ts
Fixes #92
Also remove indexes on is_active, is_frozen, start_at, is_started. Those fields are not really used, they are not part of the interview workflow and mostly all have the same value. They might as well be dropped to free the space they take.
=> migrations: Add an index on uuid field

packages/evolution-legacy/src/components/admin/ValidateSurvey.js, packages/evolution-legacy/src/components/survey/Survey.js
Let the Survey and ValidateSurvey components load preferences from server when the component is mounted.
=> Update Transition to latest main

example/demo_survey/src/survey/widgets/householdMembers.tsx
The translation types have been update and do not support simple functions anymore. The result was `[Object (object)]`. Return an html string instead.
=> demo_survey: Fix the select person widget

example/demo_survey/src/survey/widgets/home.tsx, example/demo_survey/src/survey/widgets/visitedPlaces.tsx, packages/evolution-common/src/services/widgets/WidgetConfig.ts, packages/evolution-frontend/src/components/inputs/InputMapFindPlace.tsx, packages/evolution-frontend/src/components/inputs/InputMapPoint.tsx, packages/evolution-frontend/src/components/inputs/__tests__/InputMapFindPlace.test.tsx, packages/evolution-frontend/src/components/inputs/__tests__/InputMapPoint.test.tsx, packages/evolution-frontend/src/components/inputs/maps/InputMapTypes.tsx, packages/evolution-frontend/src/components/inputs/maps/google/InputMapGoogle.tsx
This adds the necessary functionality to fix issue https://github.com/chairemobilite/od_mtl_2023/issues/401.
Tests currently fail... not quite sure why.
=> Add a new 'size' property to change the size of icons on map widgets

example/demo_survey/src/survey/sections.ts, example/demo_survey/src/survey/widgets/segments.tsx, packages/evolution-frontend/src/components/inputs/InputSelect.tsx, packages/evolution-frontend/src/components/inputs/__tests__/InputSelect.test.tsx, packages/evolution-frontend/src/components/inputs/__tests__/__snapshots__/InputSelect.test.tsx.snap
Fixes #130
Select choices can be separated in groups with group labels. If the label is set to an empty string, instead of adding an indented optgroup with an empty label, add a disabled horizontal line option to separate the group from the rest.
Inpired from this stackoverflow answer: https://stackoverflow.com/questions/899148/html-select-option-separator
Update the car driver's parking question to split in group with empty label. And re-activate the dwelling type question, for an example with groups with labels.
=> inputSelect: Add line separator for groups without label

packages/evolution-frontend/src/components/inputs/maps/google/InputMapGoogle.tsx
Relevant issue: https://github.com/chairemobilite/od_mtl_2023/issues/573
There was already a fix for this bug, but it wasn't applied in all cases.
=> Fix issue where geocoding zoom would be too high if there was a single result

packages/evolution-backend/src/api/interviews.routes.ts, packages/evolution-backend/src/api/survey.user.routes.ts, packages/evolution-backend/src/api/survey.validation.routes.ts, packages/evolution-backend/src/models/__tests__/interviews.db.test.ts, packages/evolution-backend/src/models/__tests__/interviewsAccesses.db.test.ts, packages/evolution-backend/src/models/interviews.db.queries.ts, packages/evolution-backend/src/models/interviewsAccesses.db.queries.ts, packages/evolution-backend/src/models/migrations/20230627151700_createUserLoggingTbl.ts, packages/evolution-backend/src/services/interviews/__tests__/interviews.test.ts, packages/evolution-backend/src/services/interviews/interviews.ts, packages/evolution-backend/src/services/logging/__tests__/queryLoggingMiddleware.test.ts, packages/evolution-backend/src/services/logging/loggingTypes.ts, packages/evolution-backend/src/services/logging/queryLoggingMiddleware.ts, packages/evolution-common/src/services/interviews/interview.ts, packages/evolution-legacy/src/apps/admin/server/routes.js, packages/evolution-legacy/src/apps/participant/server/routes.js
Fixes #43 
Add a database table, which tracks users who access a given interview, counting the number of edits done in the interview, with start and update timestamps
The express routes to open and update the interview use an additional middleware, which saves the user access to the interview. In the admin application, the middleware saves the data to the table described above. In the participant applicaiton, it does nothing.
The previous _editingUsers field in the responses is dropped and the statEditingUsers function is updated accordingly.
=> logging: use a logging middleware to log user accesses to interviews

example/demo_survey/locales/en/survey.json, example/demo_survey/locales/fr/survey.json, locales/en/main.json, locales/fr/main.json, packages/evolution-frontend/src/components/pageParts/ConsentAndStartForm.tsx, packages/evolution-frontend/src/components/pageParts/__tests__/ConsentAndStartForm.test.tsx, packages/evolution-frontend/src/components/pageParts/__tests__/__snapshots__/ConsentAndStartForm.test.tsx.snap, packages/evolution-legacy/src/components/survey/HomePage.js
Fixes #128
Create a new widget with a consent checkbox and the start button.
By default, the main:AgreementText in evolution is empty, so there won't be a checkbox. If the `survey:homepage:AgreementText` translation is defined in a project, it will be displayed next to a checkbox. This checkbox must be checkbox for the button to go to the main login page.
If the checkbox is not checked, the `survey:homepage:ErrorNotAgreed` text is displayed. It falls back to a default error message indicating to check the box.
=> homepage: add a consent checkbox to agree to usage of data

packages/evolution-frontend/src/components/inputs/InputMultiselect.tsx, packages/evolution-frontend/src/components/inputs/__tests__/InputMultiselect.test.tsx, packages/evolution-frontend/src/components/inputs/__tests__/__snapshots__/InputMultiselect.test.tsx.snap
Fixes #150
Do not add a shortcut button for an option that is not available in the choices.
=> multiselect: Make sure shortcut options are available

packages/evolution-legacy/src/components/survey/Button.js
Ideally this should be done in InputButton, but some surveys still use the Button.js class from evolution-legacy.
When a survey was loading, this button used to be changed to a label (ex: "Loading..."). However, since this label was smaller than the button, the content below would be moved slightly which would be quite annoying.
Now, instead of replacing the button with a label, we simply disable it so it is not clickable anymore. Since the height does not change, the flickering problem is solved.
Ideally, the property would be renamed disabledWhenRefreshing, but since this class will eventually be replaced by InputButton, I am keeping it as-is to avoid breaking changes.
=> Remove 'Loading...' label for button, instead just disable the button

packages/evolution-legacy/src/styles/survey/_survey.scss
Keeping the top corners square gives a better look.
=> Visited places cards: only round bottom corners

packages/evolution-frontend/src/components/inputs/maps/google/InputMapGoogle.tsx
You can still see them, but you can't get the popup anymore. You can still click to move the marker there. Fixes #158
=> Disable the ability to click on POIs on the Google Map

packages/evolution-common/src/services/widgets/WidgetConfig.ts, packages/evolution-frontend/src/components/inputs/InputCheckbox.tsx, packages/evolution-frontend/src/components/inputs/InputChoiceSorting.ts, packages/evolution-frontend/src/components/inputs/InputRadio.tsx, packages/evolution-frontend/src/components/inputs/__tests__/InputChoiceSorting.test.ts
With the use of the new parameters, radio and checkbox type questions can have their answers aligned by column and row and have their answers ordered vertically or horizantally. Use 'alignChoices' to have the options aligned, 'columns' to target a number of columns , 'rows' to target a number of rows, 'alignment' to specify in wich direction to order the choices, 'customAlignmentLengths' to specify the length of each row or column. When using custom lengths in horizontal alignment, the first row must be the longuest.
=> Add sorting and display options to a question's answers.

packages/evolution-frontend/src/components/inputs/maps/google/InputMapGoogle.tsx
Ideally we would just get the value from the i18n system to allow changing the language when the map is loaded. Unfortunately, @react-google-maps does not allow changing the map language once the map is loaded. See https://github.com/chairemobilite/evolution/pull/114#issuecomment-1568529296 for a discussion
So, for now, we will at least allow seting the map language from the config file. If a survey is done mostly in, for example Québec, then we can set the language to french in the config file.
=> Change map language from config.js

.github/workflows/evolution.yml, Dockerfile, example/demo_survey/package.json, packages/evolution-backend/package.json, packages/evolution-common/package.json, packages/evolution-frontend/package.json, packages/evolution-legacy/package.json
Fixes #165
All packages now require node 18+
Add the --openssl-legacy-provider flag to yarn build scripts to support current webpack.
=> Drop node 16 support

package.json, packages/evolution-interviewer/.eslintignore, packages/evolution-interviewer/.eslintrc.json, packages/evolution-interviewer/.prettierignore, packages/evolution-interviewer/.prettierrc.js, packages/evolution-interviewer/jest.config.js, packages/evolution-interviewer/jest.sequential.config.js, packages/evolution-interviewer/package.json, packages/evolution-interviewer/src/client/config/i18nextExtra.config.ts, packages/evolution-interviewer/src/client/services/interviewers/interviewerSupport.ts, packages/evolution-interviewer/src/server/services/auth/__tests__/roleDefinition.test.ts, packages/evolution-interviewer/src/server/services/auth/roleDefinition.ts, packages/evolution-interviewer/tsconfig.json
Fixes #175
This interviewer module adds roles for interviewers, which are users allowed to read or update any interviews and interviewer supervisor, which have the same permissions as interviewers, but also manage interviewers.
This module also adds support for an interviewer mode in the interview, which can be used to change labels for this mode, or by widgets.
To use, the server admin application needs to call the `roleDefinition` default function to add the roles.
The frontend admin application needs to import the `interviewerSupport` file and add the interviewer options to the application configuration.
=> Add an evolution-interviewer node module for interviewer support

locales/en/main.json, locales/fr/main.json, packages/evolution-interviewer/src/client/services/interviewers/interviewerSupport.ts
Also, return the modified config instead of simply modifying in place. Add a default text for interviewer/participant modes in the evolution locales.
=> interviewer: use partial configuration as arguments

example/demo_survey/src/admin/app-admin.tsx, example/demo_survey/src/app-survey.tsx, packages/evolution-frontend/package.json, packages/evolution-frontend/src/components/pageParts/interviews/InterviewSearchList.tsx, packages/evolution-frontend/src/components/pages/InterviewsByAccessCode.tsx, packages/evolution-frontend/src/config/application.config.ts, packages/evolution-frontend/src/contexts/InterviewContext.ts, packages/evolution-legacy/src/actions/survey/survey.js
* This allows to automatically create a new survey if there are none for a given access code (with the autoCreate=true query string parameter)
* Also pre fill the responses from the query string from a white list of fields allowing this.
This will allow phone interviewers to generate a link which would open an interview with the access code and phone number already filled from the url itself. Useful for the Quebec-Levis survey
=> interview list: auto create new interviews and prefill answers from query

packages/evolution-frontend/src/actions/Survey.ts, packages/evolution-frontend/src/actions/__tests__/Survey.test.ts
Based on my small scale testing, this seems to fix the issue. In my database, _language was always null, but now it seems to correctly show "fr" or "en". Fixes https://github.com/chairemobilite/od_mtl_2023/issues/374
=> Fix language not being saved in the interview responses

packages/evolution-frontend/package.json, packages/evolution-frontend/src/components/inputs/maps/InputMapTypes.tsx, packages/evolution-frontend/src/components/inputs/maps/google/InputMapGoogle.tsx
fixes #219
Adds the platform type when a point on the map is dragged or clicked
=> InputMapGoogle: Add the platform to the point properties

packages/evolution-common/src/services/widgets/WidgetConfig.ts, packages/evolution-frontend/src/actions/utils/WidgetOperation.ts
when toggling between hide/show conditional status, this is useful if you want to use two different widget questions for the same value, and toggle between them according to a condition. Without this config, whenever the condition is switched back to show after a hide, the hide assigned value is replaced by the default or empty value. This is also useful to hide a question when a condition is met, but keep its assigned value active between hide and show toggles
=> add a way to keep the assigned value intact

packages/evolution-legacy/src/components/survey/Survey.js
we do not use the submit event at all, since buttons have their own onClick actions, and the enter/space key trigger on these button is correctly sent to onClick action for screen readers and ARIA
=> disable form submit default so it does not trigger on any key

locales/en/admin.json, locales/fr/admin.json, packages/evolution-backend/src/api/survey.validation.routes.ts, packages/evolution-backend/src/models/migrations/20230912214500_changeInterviewFreeze.ts, packages/evolution-backend/src/services/interviews/__tests__/interview.test.ts, packages/evolution-backend/src/services/interviews/interview.ts, packages/evolution-common/src/services/interviews/interview.ts, packages/evolution-legacy/src/actions/survey/survey.js, packages/evolution-legacy/src/components/admin/ValidateSurvey.js, packages/evolution-legacy/src/components/admin/validation/InterviewSummary.js, packages/evolution-legacy/src/components/admin/validation/ValidationOnePageSummary.js
fixes #238, fixes #239, fixes #240
* Move the copy to validated_data to a single backend function, and add the copy timestamp
* The backend now takes care to freeze the interviews whenever they are set as valid or completed by a validator, otherwise it can still be edited
* Add a migration to automatically unfreeze any interview whose valid/completed statuses are not set
* Add a warning in the one page summary if the responses were modified since the copy
=> validations: Change how interviews are frozen

packages/evolution-frontend/src/components/inputs/InputRadioNumber.tsx, packages/evolution-frontend/src/components/inputs/__tests__/__snapshots__/InputRadioNumber.test.tsx.snap, packages/evolution-frontend/src/components/survey/__tests__/__snapshots__/Question.test.tsx.snap
This reverts commit ce4b57d438c085a4ea932d8b64e7355184f61d51.
This interferes with the mechanism that is used to automatically focus on an invalid question on page load. Having the autoFocus tag here means that the survey focuses on this text field instead, which is not desirable.
=> Revert "InputRadioNumber: add auto focus tag"

packages/evolution-backend/src/models/__tests__/interviews.db.test.ts
The updated_at are null when the interview has not been updated, so only 1 interview was updated and has a timestamp gt 0.
This test has been failing for a while.
=> Fix sequential tests

packages/evolution-backend/src/models/__tests__/interviews.db.test.ts, packages/evolution-backend/src/models/interviews.db.queries.ts, packages/evolution-backend/src/services/interviews/interviews.ts
Add the possibility to not include audits, and whether to include responses, validated_data, none, both, or validated_data only if available otherwise responses
=> db: Allow to customize the streaming query

packages/evolution-common/src/services/parsers/ParserFunction.ts, packages/evolution-common/src/services/widgets/PathConfig.ts
for better access to configuration of each path, which will be useful in the future when we will merge all widget/path configs for both the questionnaire and the admin with validations
=> add parser function and path config

locales/fr/auth.json
Voir <https://www.rfc-editor.org/rfc/rfc2606.html#section-3>
```exemple.com``` mène à un site parké/suspect.
=> Renommer le domaine exemple.com en example.com (voir RFC 2606).

packages/evolution-backend/src/models/__tests__/adminViews.db.test.ts, packages/evolution-backend/src/models/adminViews.db.queries.ts, packages/evolution-backend/src/models/migrations/20231006093500_createAdminViewsTbl.ts
fixes #296
This adds support for materialized views in surveys. The server can register the view with the `registerView` method, with the corresponding SQL query at startup. If the view already exists, if verifies if the query is the same as previously. If not, the view will be dropped and re-created.
The view can be refreshed, queried with all or a subset of the fields, or using a groupBy/count query.
This commit just provides the API for view support. Surveys can then create their own views and query them. It will provide a less memory intensive way to parse all surveys for various information for monitoring purposes.
=> admin: Support materialized views for monitoring

packages/evolution-backend/src/models/__tests__/adminViews.db.test.ts, packages/evolution-backend/src/models/adminViews.db.queries.ts
fixes #307
If a survey has many admin views, they can all be refreshed with this function.
=> adminViews: Add function to refresh all views

packages/evolution-backend/src/models/migrations/20231013123200_addAccessCodeIndex.ts
fixes #315
This increases performance of listing interviews by more than 10 times. From local benchmarks in a 15K record database, it does not affect perceptibly the performances of the responses updates or the survey flow. The database update/insert times are within 2% with/without the index, less than the normal variability.
=> db: Add an index on the responses.accessCode field

packages/evolution-backend/src/models/interviews.db.queries.ts
fixes #316
Instead of extracting epoch to match a timestamp in parameter, the timestamp is converted to a database timestamp to select on the created_at/updated_at fields directly. This allows to use the index on those fields and performs better.
=> db: select interviews with created_at/udpated_at fields

packages/evolution-common/src/services/baseObjects/BaseHousehold.ts, packages/evolution-common/src/services/baseObjects/BaseInterview.ts, packages/evolution-common/src/services/baseObjects/BasePerson.ts, packages/evolution-common/src/services/baseObjects/__tests__/BaseHousehold.test.ts, packages/evolution-common/src/services/baseObjects/__tests__/BaseInterview.test.ts, packages/evolution-common/src/services/baseObjects/__tests__/BasePerson.test.ts
the validateParams function returns errors that prevent the object from being created. Only typing should be checked here, otherwise we cannot validate the interview in the admin dashbord. So validating an email, a phone number or a category should be done in survey audits instead
=> remove more complex validations that should be in audits

packages/evolution-backend/src/services/adminExport/exportToCsvByObjectWorkerPool.ts
fixes #348
Add the is_valid, is_completed and is_validated flags in the interview's exported csv file.
=> adminExport: Add validation flags in interview csv file

packages/evolution-backend/src/models/__tests__/adminViews.db.test.ts, packages/evolution-backend/src/models/adminViews.db.queries.ts, packages/evolution-backend/src/models/migrations/20231122131300_addUniqueForAdminViews.ts
fixes #351
Add a `unique_field` field to the `sv_materialized_views`. If set, this will create a unique index on the materialized view, allowing it to be refreshed concurrently, thus not locking the table and blocking the queries to it.
=> adminViews: Add unique field to materialized views

locales/en/server.json, locales/fr/server.json, packages/evolution-backend/src/services/auth/participantAuthModel.ts
Add sendWelcomeEmail in createAndSave function
I put sendWelcomeEmail only in createAndSave, so it's only going to call if the user is new and the config is auth.welcomeEmail === true. 
I got server.json if the survey don't have a customServer file, but customServer file is the best way to implement the welcome email.
=> Add sendWelcomeEmail in createAndSave function

packages/evolution-frontend/src/components/hoc/WithPreferencesHoc.tsx, packages/evolution-legacy/src/components/admin/ValidateSurvey.js, packages/evolution-legacy/src/components/survey/Survey.js
The `WithPreferencesHoc` component loads the preferences upon first mount, then displays the wrapped component. A loading page is shown while preferences are loading.
The Survey and ValidateSurvey components use this HOC.
=> preferences: Add a HOC component to make sure preferences are loaded

packages/evolution-backend/src/models/__tests__/interviews.db.test.ts, packages/evolution-backend/src/models/interviews.db.queries.ts, packages/evolution-frontend/src/components/pageParts/validations/InterviewListComponent.tsx, packages/evolution-frontend/src/components/pageParts/validations/ValidationAuditFilter.tsx
The audit filter uses a subquery to the sv_audits table instead of the audits field of the interviews table.
The list of validation errors come from the sv_audits table as well.
Sequential tests are updated accordingly.
=> audits: Use new audit table for audit filter

packages/evolution-backend/src/api/survey.validation.routes.ts, packages/evolution-backend/src/config/projectConfig.ts, packages/evolution-backend/src/services/audits/Audits.ts, packages/evolution-backend/src/services/audits/__tests__/Audits.test.ts, packages/evolution-common/src/services/audits/types.ts
frontend will need to recreate survey objects for stats and summary, so we need to get a serialized version from the server during audit
=> include survey objects when auditing

packages/evolution-frontend/src/components/pageParts/validations/InterviewByCodeFilter.tsx
This uses the access code index for direct access to the interviews instead of a full table scan. That should improve query performance for large surveys.
=> validations: Use equality for access code search

packages/evolution-common/src/services/baseObjects/BaseInterview.ts, packages/evolution-common/src/services/baseObjects/BaseJourney.ts, packages/evolution-common/src/services/baseObjects/BaseVisitedPlace.ts, packages/evolution-common/src/services/baseObjects/__tests__/BaseInterview.test.ts, packages/evolution-common/src/services/baseObjects/__tests__/BaseJourney.test.ts, packages/evolution-common/src/services/baseObjects/__tests__/BaseVisitedPlace.test.ts
to make sure timezones with Date/moment do not shift days
=> use date strings instead of Dates in survey objects

packages/evolution-common/src/services/baseObjects/Survey.ts, packages/evolution-common/src/services/baseObjects/__tests__/Survey.test.ts
like we did for othe survey objects, to make sure there is no shift caused by timezone management in javascript Date object
=> convert Survey dates to strings

packages/evolution-generator/src/helpers/generator_helpers.py, packages/evolution-generator/src/scripts/generate_choices.py, packages/evolution-generator/src/scripts/generate_conditionals.py, packages/evolution-generator/src/scripts/generate_input_range.py, packages/evolution-generator/src/scripts/generate_section_configs.py, packages/evolution-generator/src/scripts/generate_sections.py, packages/evolution-generator/src/scripts/generate_survey.py, packages/evolution-generator/src/scripts/generate_widgets.py, packages/evolution-generator/src/scripts/generate_widgets_config.py, packages/evolution-generator/src/types/inputTypes.ts, packages/evolution-generator/src/types/sectionsTypes.ts
fix: #402
Generate configs with Generator. This should accelerate the process of creating a new survey. It's always take some time to do that manually, and it's a pain. I also added new Sections types (for example WidgetsNames). 
Note: We still need to create Groups and Preload until we find a better solution.
=> Generate Sections Configs With Generator and add new Sections types

packages/evolution-generator/src/common/validations.tsx, packages/evolution-generator/src/types/inputTypes.ts
Add car and householdSize validations
Add defaultValue type
We are using some validations in many surveys.
=> Add car and householdSize validations

packages/evolution-generator/src/types/inputTypes.ts
Add new input types for the Evolution-Generator
Remove optional interview and path on input types for function
=> Add new input types for Evolution-Generator

packages/evolution-generator/src/helpers/generator_helpers.py, packages/evolution-generator/src/scripts/generate_libelles.py, packages/evolution-generator/src/scripts/generate_section_configs.py, packages/evolution-generator/src/scripts/generate_sections.py, packages/evolution-generator/src/scripts/generate_survey.py, packages/evolution-generator/src/scripts/generate_widgets.py, packages/evolution-generator/src/scripts/generate_widgets_configs.py
Sometimes, we don't want to use every script from Generator for a specific survey.
Also, it's going to be way easier to configs for the new user working with Generator.
Add enabled_scripts for every script of Generator
Take the sections from Excel and not from generatorConfigs.yaml 
Remove any useless variables from generatorConfigs.yaml 
Use a survey_folder_path to keep the generator survey consistent
I can't even take a screenshot of the old configs, because it's too long (51 lines vs 13 lines).
=> Simplify generatorConfigs.yaml

packages/evolution-generator/src/helpers/generator_helpers.py, packages/evolution-generator/src/scripts/generate_sections.py, packages/evolution-generator/src/scripts/generate_widgets_configs.py
Add get_sections_names helper function
Change sections_names ordering with List and not set
Add types to rows and headers
The widgetsConfigs.tsx and sections.ts were not ordering the sections_names in good order when using set(). Now it's good.
=> Add get_sections_names helper function

packages/evolution-backend/src/services/interviews/__tests__/interviews.test.ts, packages/evolution-backend/src/services/interviews/interviews.ts
It should not depend on the frontend's section preload to have this important data in the interview.
=> interview: Make sure _startedAt is initialized at interview creation

packages/evolution-generator/src/types/inputTypes.ts
instead of single `fr`/`en` object type.
=> generator: Use the `Label` type for translations

packages/evolution-backend/src/api/survey.user.routes.ts, packages/evolution-backend/src/services/interviews/__tests__/interview.test.ts, packages/evolution-backend/src/services/interviews/__tests__/serverFieldUpdate.test.ts, packages/evolution-backend/src/services/interviews/interview.ts, packages/evolution-backend/src/services/interviews/serverFieldUpdate.ts, packages/evolution-frontend/src/actions/Survey.ts
The server field update callback can now also return an array with the
fields to update, as well as a string representing an URL to redirect
to. This URL is returned from the `updateInterview` call.
The `/survey/updateInterview` route can return a response with the
status of `redirect`, along with a `redirectUrl` field. If so, the
client should redirect to this URL directly.
=> Let serverFieldUpdate return a redirection URL

packages/evolution-generator/src/common/defaultInputBase.tsx, packages/evolution-generator/src/scripts/generate_widgets.py, packages/evolution-generator/src/types/inputTypes.ts
The widgets can have 2 additional properties: `twoColumns` and `containsHtml` that can be defined in the excel file.
The row is passed to the widget generator function, which can then request to generate any additional properties. A function for common question widget properties is added to generate those two properties.
Also, they are removed from the base input types and put in the input types themselves.
=> generator: Add twoColumns and containsHtml common properties

packages/evolution-generator/src/common/validations.tsx
The validation message says we need to be in Canada, but the regex corresponds to Quebec. This fixes for any canadian postal code. Surveys can fine-tune their territory handling afterwards.
=> generator: Fix postal code regex for canadian postal code

packages/evolution-generator/src/scripts/generate_conditionals.py
fixes #450
If the value is a boolean, it is written as such in the generated code
=> generator: Let conditional value properly handle booleans

locales/en/main.json, locales/fr/main.json, packages/evolution-frontend/src/components/inputs/InputMapFindPlace.tsx, packages/evolution-frontend/src/components/inputs/InputMapPoint.tsx, packages/evolution-frontend/src/components/inputs/maps/google/GoogleGeocoder.tsx
fixes #456
The no result is handled internally by the widget and it displays an error message corresponding to the result of the query: either no result or error.
=> input map: Handle the geocode API's no result

packages/evolution-generator/src/common/defaultInputBase.tsx, packages/evolution-generator/src/types/inputTypes.ts
fixes #454
The correct property to use is `keyboardInputMode` from the WidgetConfig types.
=> generator: Let number textboxes use numeric keyboard

locales/en/main.json, locales/fr/main.json, packages/evolution-frontend/src/components/pages/SurveyErrorPage.tsx, packages/evolution-frontend/src/services/errorManagement/errorHandling.ts, packages/evolution-legacy/src/apps/participant/client/SurveyRouter.js
fixes #457
Instead of redirecting to `maintenance` page, the user is redirected to an `error` page, which indicates an error occurred, advises to check internet connection and links back to the survey.
The following locale strings can be customized by surveys, in the survey.json file:
* BackToSurveyPage
* AnErrorOccurred
* MakeSureReliableConnection
* ErrorPersistsWhatToDo
=> Add a `SurveyErrorPage` to which to redirect on error

.github/workflows/evolution.yml
Old version were deprecated, see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
=> Upgrade github actions in main workflow

packages/evolution-frontend/src/components/pages/SurveyErrorPage.tsx
This will allow surveys to add html tags to the text for the survey error page, like email links.
=> errorPage: allow html in translation strings

example/demo_survey/src/server.ts, example/demo_survey/src/server/serverFieldUpdate.ts, packages/evolution-backend/src/services/interviews/serverFieldUpdate.ts, packages/evolution-frontend/src/actions/Survey.ts
fixes #471
Document that when redirecting to external URLs the user will be logged out
Activate the serverFieldUpdate callbacks in the demo survey and include an example of redirection when the access code is 1133-1133, the participant is redirected to evolution's github page.
Call the logout after setting the href location.
=> urlRedirect: logout from the application when redirecting

.gitignore, README.md, example/demo_survey/package.json, example/demo_survey/tests/test-survey-UI.spec.ts, package.json, packages/evolution-backend/package.json, packages/evolution-frontend/.eslintignore, packages/evolution-frontend/package.json, packages/evolution-frontend/playwright-example.config.ts, packages/evolution-frontend/tests/ui-testing/configurei18n.ts, packages/evolution-frontend/tests/ui-testing/testHelpers.ts, packages/evolution-interviewer/package.json, packages/evolution-legacy/package.json, yarn.lock
fixes #490
* Add the `testHelpers` from the MJ project into Evolution
* Add an example configuration for playwright tests
* Add a section in the readme to run those tests
* Configure translations from files, similar to chaire-lib-backend, so
that library functions can use them (for example for the anonymous
login text).
* Display screenshots on failure
=> test: Bring the playwright UI testing functionality to evolution

locales/en/admin.json, locales/fr/admin.json, packages/evolution-backend/src/api/admin.routes.ts, packages/evolution-backend/src/api/admin/exports.routes.ts, packages/evolution-frontend/src/components/admin/ExportInterviewData.tsx, packages/evolution-legacy/src/components/admin/Monitoring.js
fixes #293 and fixes #294
The ExportInterviewData widget is now part of the Status page by default. The code was taken from the od_mtl_2023 survey. It does not include the `simpleExport` from this survey that would require some generalization to make it directly to Evolution.
=> admin: Add the survey export by object widget to Evolution

packages/evolution-generator/src/scripts/generate_widgets.py, packages/evolution-generator/src/types/inputTypes.ts
The 'path' is required to resolve ${relativePath} in conditional expressions.
Add path to InfoTextInput widget and type
=> Add path to InfoTextInput widget and type

packages/evolution-frontend/src/components/survey/InfoMap.tsx
fixes #549
The bounds are initialized at every call so they can be extended the same way at every render.
=> infoMap: Fix the bounds extension to avoid extending indefinitely

example/demo_survey/src/survey/widgets/end.tsx, locales/en/main.json, locales/fr/main.json, packages/evolution-common/src/services/widgets/WidgetConfig.ts, packages/evolution-frontend/src/components/inputs/InputCheckbox.tsx, packages/evolution-frontend/src/components/inputs/InputRange.tsx, packages/evolution-frontend/src/components/inputs/__tests__/InputCheckbox.test.tsx, packages/evolution-frontend/src/components/inputs/__tests__/InputRange.test.tsx, packages/evolution-frontend/src/components/inputs/__tests__/__snapshots__/InputCheckbox.test.tsx.snap, packages/evolution-frontend/src/components/inputs/__tests__/__snapshots__/InputRange.test.tsx.snap, packages/evolution-generator/src/scripts/generate_widgets.py
fixes #539
To avoid the participant having to select a position for a question that does not apply to him, there should be a "Non applicable" option that the user can select that will disable the input range. The answer in this case, instead of a `number` will be a `string` with value `na`.
=> inputRange: add a `includeNonApplicable` property

.github/workflows/evolution.yml
This branch is the one that the 2023 surveys support and where any required change will be backported.
=> CI: force CI to run on the od_2023 branch

locales/en/admin.json, locales/fr/admin.json, packages/evolution-backend/src/api/admin/__tests__/exports.routes.test.ts, packages/evolution-backend/src/api/admin/exports.routes.ts, packages/evolution-backend/src/services/adminExport/exportAllToCsvByObject.ts, packages/evolution-backend/src/services/adminExport/exportToCsvByObjectWorkerPool.ts, packages/evolution-backend/src/services/adminExport/types.ts, packages/evolution-frontend/src/components/admin/ExportInterviewData.tsx
fixes #557
The export task receives an option parameter, which has a `responseType` field, with values 'validatedIfAvailable' or 'participant'. The exported file names will be prefixed with either validated or participant depending on the response type.
In the UI widget, there are 2 export buttons, one for each type of export.
=> exports: Allow to export validated or original responses by object

packages/evolution-legacy/src/components/survey/GroupedObject.js, packages/evolution-legacy/src/components/survey/Section.js
If a widget can have multiple types, it is preferable to use 2 widgets with conditionals mutually exclusive, or create a specific widget that can be multiple types (eg. radio or select), but allowing any type in a single widget can be tricky as there isn't much in common between a text and a radio widgets, for example, it requires to put all the possible configs for all types.
=> widgets: The type of a widget config cannot be a function

example/demo_survey/locales/en/survey.json, example/demo_survey/locales/fr/survey.json, example/demo_survey/src/survey/sections.ts, example/demo_survey/src/survey/templates/SegmentsSection.tsx, example/demo_survey/src/survey/templates/VisitedPlacesSection.tsx, example/demo_survey/src/survey/widgets/householdMembers.tsx, example/demo_survey/src/survey/widgets/segments.tsx, example/demo_survey/src/survey/widgets/visitedPlaces.tsx, packages/evolution-common/src/services/widgets/WidgetConfig.ts, packages/evolution-frontend/src/actions/utils/WidgetOperation.ts, packages/evolution-frontend/src/actions/utils/__tests__/WidgetOperation.test.ts, packages/evolution-frontend/src/components/hoc/__tests__/WithSurveyContextHoc.test.tsx, packages/evolution-frontend/src/components/survey/GroupWidgets.tsx, packages/evolution-frontend/src/components/survey/__tests__/GroupWidgets.test.tsx, packages/evolution-frontend/src/components/survey/__tests__/__snapshots__/GroupWidgets.test.tsx.snap, packages/evolution-frontend/src/components/survey/widgets/DeleteGroupedObjectButton.tsx, packages/evolution-frontend/src/components/survey/widgets/__tests__/DeleteGroupedObjectButton.test.tsx, packages/evolution-frontend/src/components/survey/widgets/__tests__/__snapshots__/DeleteGroupedObjectButton.test.tsx.snap, packages/evolution-frontend/src/contexts/SurveyContext.ts, packages/evolution-frontend/src/services/interviews/interview.ts, packages/evolution-generator/src/scripts/generate_section_configs.py, packages/evolution-generator/src/types/inputTypes.ts, packages/evolution-legacy/src/components/admin/ValidateSurvey.js, packages/evolution-legacy/src/components/survey/Section.js, packages/evolution-legacy/src/components/survey/Survey.js
There is no separate groups configuration in the section definition
anymore. Instead, all the attributes that were described there are added
to the group widget itself so there's only one place to configure the
group
** Breaking change **
* The `groupName` property is renamed to `title`
* The `groupShortname` does not exist anymore as it was not used
* The `groups` definitions in the sections need to be moved to the
corresponding widget of type `group`.
* Specific group templates may need to be updated.
* The group widget config's `shortname` field must match the last part
of the path where are stored those objects.
=> groups: Use a single group configuration for all groups

packages/evolution-frontend/tests/ui-testing/testHelpers.ts
When the date to pick is at the beginning or end of the month, sometimes, the calendar will have 2 days with the same texts. We need to pick the one with the label that contains the month.
=> playwright: fix datepicker tests when calendar shows 2 days

packages/evolution-legacy/src/components/survey/Section.js
Some widgets, like InputRange, do not have an ID (and cannot have one, as the library used does not allow to set it), but they can be invalid. To automatically scroll to the invalid question, we make sure the input has an ID before focusing on it. Otherwise, we use the other code path that just scrolls the page to make the widget visible.
=> sections: Make sure the invalid widget has an ID before focusing

packages/evolution-frontend/src/actions/Survey.ts
If a server field update has changed the `_activeSection` field, the update interview redux action should correctly update the current section before dispatching the updated data, otherwise it renders empty surveys.
=> survey: Verify section change from server in redux action

example/demo_survey/src/survey/sections.ts, packages/evolution-common/src/services/widgets/WidgetConfig.ts, packages/evolution-common/src/utils/__tests__/helpers.test.ts, packages/evolution-common/src/utils/helpers.ts, packages/evolution-frontend/src/actions/Survey.ts, packages/evolution-frontend/src/actions/__tests__/Survey.test.ts, packages/evolution-legacy/src/actions/survey/survey.js, packages/evolution-legacy/src/helpers/survey/helper.js, packages/evolution-legacy/src/helpers/survey/survey.js
Document and type and function parameters
Also type those functions in the InterviewUpdateCallbakcs type.
** Breaking change **
If surveys were calling directly the removeGroupedObjects helper function, the order of the argument has changed for consistency with those of the addGroupedObjects function. It is now `interview, paths` instead of the reverse.
=> survey: Move the add/remove grouped object actions to typescript

packages/evolution-generator/src/types/inputTypes.ts
There is no type for InputDatePicker, it's easy to make errors with this input.
Add InputDatePicker type in inputTypes.ts
=> Add InputDatePicker type in inputTypes.ts

packages/evolution-common/src/services/interviews/interview.ts, packages/evolution-common/src/services/odSurvey/__tests__/helpers.test.ts, packages/evolution-common/src/services/odSurvey/helpers.ts, packages/evolution-common/src/tests/surveys/index.ts, packages/evolution-common/src/tests/surveys/testCasesInterview.ts
This adds various helper function taken from surveys, for self declared persons, trips getters, visited places name getter and segments getters. Add tests for all these functions.
Also add object fields that may be present for those helpers.
@samuel-duhaime  @kaligrafy This commit was previously part of my 15-min segment section branch, but I need them for longue distance too (to get those functions out of the helper file that imports frontend data and thus cannot run in the backend)
=> survey: Add helper functions for odSurvey and additional responses field

example/demo_survey/src/survey/sections.ts, example/demo_survey/src/survey/templates/SegmentsSection.tsx, example/demo_survey/src/survey/templates/VisitedPlacesSection.tsx, example/demo_survey/src/survey/widgets/home.tsx, example/demo_survey/src/survey/widgets/profile.tsx, example/demo_survey/src/survey/widgets/segments.tsx, example/demo_survey/src/survey/widgets/visitedPlaces.tsx, packages/evolution-common/src/services/odSurvey/__tests__/helpers.test.ts, packages/evolution-common/src/services/odSurvey/helpers.ts, packages/evolution-common/src/utils/helpers.ts, packages/evolution-legacy/src/helpers/survey/helper.js
fixes #603
All new OD survey helpers take an object as argument, instead of positioned ones. This will ensure uniformity, as some helpers to come will have more arguments. It also simplifies specifying optional arguments.
The helper functions that were aliases to the OD survey ones keep their previous signature, to reduce breaking changes as these can possibly be used by [un-tested/any-typed] surveys.
=> od helpers: Replace arguments with a single object

packages/evolution-legacy/src/styles/survey/_question.scss
For: https://github.com/chairemobilite/od_mj_2023/issues/271
Note: I initially thought I needed to improve the performance of the InputRange, but then I discovered there was a hidden CSS transition of 0.3 seconds, so I was able to resolve the issue with just 1 line of code!
Remove the transition on InputRange so the slider is not slow anymore.
Before:
[bug-range-input-firefox.webm](https://github.com/chairemobilite/od_mj_2023/assets/78976679/76991fff-df4b-4a44-8b6a-4a58621e6a7e)
After:
[Screencast from 2024-07-22 11:35:46 AM.webm](https://github.com/user-attachments/assets/e0aa3af5-d085-4255-995f-01fba30dec96)
=> Remove the transition on InputRange

example/demo_survey/src/server/serverFieldUpdate.ts, packages/evolution-backend/package.json, packages/evolution-backend/src/api/express-session.d.ts, packages/evolution-backend/src/api/survey.user.routes.ts, packages/evolution-backend/src/services/interviews/__tests__/interview.test.ts, packages/evolution-backend/src/services/interviews/__tests__/serverFieldUpdate.test.ts, packages/evolution-backend/src/services/interviews/interview.ts, packages/evolution-backend/src/services/interviews/serverFieldUpdate.ts
fixes #582
Add an extra parameter for server update callbacks, so that callbacks
that have time-consuming operations (like routing calculations) can
register the operation, which can then execute without blocking the
current client update call.
The callbacks can return quickly empty or other values, but register
an operation, identified by a `opName` and `opUniqueId`. The `opName`
ensures that only one operation for that name will be considered. The
`opUniqueId` allows to cancel any previous operation with the same name.
The `operation` to register is a function that receives a `isCancelled`
function and returns a promise that will run in the background. The
promise should return the values by path to set in the interview. The
interview will be saved with the new values and those can be …
=> server: Add a deferred server update callback mechanism

packages/evolution-generator/src/scripts/generate_UI_tests.py
I think this was a bad idea, to have an error if the questionName, path, or inputType is None. For example, we don't always have the path for Custom inputType, so it's better to still generate the template-tests-UI.ts even without that. I cannot use this script in MJ without this pull request.
Remove invalid error in generate_UI_tests.
=> Generator: Remove invalid error in generate_UI_tests

packages/evolution-common/src/config/__tests__/project.config.initialized.test.ts, packages/evolution-common/src/config/__tests__/project.config.test.ts, packages/evolution-common/src/config/project.config.ts, packages/evolution-common/src/services/odSurvey/helpers.ts, packages/evolution-frontend/src/components/inputs/InputMapPoint.tsx
Add a file in evolution-common, `project.config.ts`, which extends chaire-lib's project configuration types.
Start documenting a few of the evolution project's configuration property and set default values for them.
Import this new project.config file instead of the chaire-lib's one, to be able to call directly the typed properties.
=> config: Type the Evolution-specific configuration options

packages/evolution-generator/src/common/validations.tsx
Generator: Add bikeNumberValidation and fix carNumberValidation
=> Generator: Add bikeNumberValidation and fix carNumberValidation

.env.example, packages/evolution-backend/src/config/__tests__/projectConfig.test.ts, packages/evolution-backend/src/config/projectConfig.ts, packages/evolution-backend/src/services/routing/RouteCalculationFromTransition.ts, packages/evolution-backend/src/services/routing/__tests__/RouteCalculation.test.ts, packages/evolution-backend/src/services/routing/__tests__/RouteCalculationFromTransition.test.ts, packages/evolution-backend/src/services/routing/index.ts, packages/evolution-backend/src/services/routing/types.ts
This adds a function that requests route calculations from the Transition public API
It also adds a routing-function agnostic function that surveys can use for calculation.
Transiton URL and username/password can be set in the survey configuration at application startup.
=> Routing: use transition public API for routing in surveys

packages/evolution-generator/src/common/validations.tsx
Quand on a trop de vehicules selon la taille du menage, le message d'erreur dit le nombre maximum de vehicules. Change l'ordre de deux verifications pour message d'erreur plus naturel. Change aussi "less that or equal to" a "at most"
Fixes #385
=> Ecrire nombre de vehicules selon la taille de menage dans message d'erreur

packages/evolution-frontend/src/components/inputs/InputMapFindPlace.tsx, packages/evolution-frontend/src/components/inputs/InputMapPoint.tsx, packages/evolution-frontend/src/components/inputs/__tests__/__snapshots__/InputMapFindPlace.test.tsx.snap, packages/evolution-frontend/src/components/inputs/__tests__/__snapshots__/InputMapPoint.test.tsx.snap
Geocoder button will not render until the google map is finished loading, avoiding issues on some playwright tests where the button will be clicked too quickly on faster machines.
Fix: #621
=> Fix testing issue with google maps not being loaded.

packages/evolution-frontend/tests/ui-testing/testHelpers.ts
When running the playwright tests on remote instances, like the test ones, that have HTTPs urls, the tests often the page with an SSL_CERT_ERROR. Ignoring those errors allow to run the tests anyway.
=> playwright: Allow to ignore https error when initializing context

packages/evolution-legacy/src/helpers/survey/helper.js
This will make sure the validation page does not throw an error if the persons do not have journeys defined.
=> helpers: Fix default helpers when journey is undefined

packages/evolution-common/src/services/widgets/WidgetConfig.ts, packages/evolution-frontend/src/components/inputs/InputMapFindPlace.tsx, packages/evolution-frontend/src/components/inputs/InputMapPoint.tsx, packages/evolution-frontend/src/components/inputs/maps/google/InputMapGoogle.tsx, packages/evolution-generator/src/types/inputTypes.ts
fixes #665
The `geocodingQueryString` function now returns either a string or an array of objects containing a `queryString` and a `zoom`. The first object is geocoded and if results are returned, they are used and the map zooms at the specified level. If no results are returned, the next query string object is geolocated, etc.
=> mapFindPlace: Allow multiple geocoding query string and zooms

packages/evolution-frontend/src/actions/utils/WidgetOperation.ts, packages/evolution-legacy/src/components/admin/validation/InterviewSummary.js
Return valuesByPath in widget preparation if there is no widget, but the section is validationOnePager
Use arrow functions in InterviewSummary, since it is javascript and not typescript.
=> admin: Fix the validation link callbacks

locales/en/auth.json, locales/fr/auth.json, packages/evolution-frontend/src/components/pages/auth/AuthPageHOC.tsx
Add a message when no auth method is there on the login page 
Note: We add this message for surveys that can only be authenficate with an access token from an invitation, for example with Leo panel.
Login page
=> Add a message when no auth method is there on the login page

example/demo_survey/src/survey/widgets/home.tsx, example/demo_survey/tests/test-input-validation.UI.spec.ts, packages/evolution-generator/src/common/validations.tsx
Change the regex for the postal code validation so that it doesn't accept letters not valid for canadian codes.
Also adds the case insensitive flag to shorten the regex and not repeat letters with different cases. 
Adds some more tests for the postal code to the input validation test. 
Fix: #663
=> Improve postal code verification.

packages/evolution-backend/src/services/routing/RouteCalculationFromTransition.ts, packages/evolution-backend/src/services/routing/__tests__/RouteCalculation.test.ts, packages/evolution-backend/src/services/routing/__tests__/RouteCalculationFromTransition.test.ts, packages/evolution-backend/src/services/routing/index.ts, packages/evolution-backend/src/services/routing/types.ts
Renamed the default export for the time and distance from transition API to `getTimeAndDistanceFromTransitionApi`
Add a function to call the transition API's summary endpoint to retrieve summary for a trip
Expose this method as a `getTransitSummary` function in evolution-backend's `routing` service.
=> Add summary call using the Transition API

packages/evolution-backend/src/api/survey.validation.routes.ts, packages/evolution-frontend/src/components/pageParts/validations/InterviewList.tsx, packages/evolution-legacy/src/actions/survey/survey.js, packages/evolution-legacy/src/components/admin/Validation.js, packages/evolution-legacy/src/components/admin/validation/InterviewSummary.js, packages/evolution-legacy/src/components/admin/validation/ValidationOnePageSummary.js
fixes #680
This also simplifies the interview loading from the validation list.
The `/interviewSummary` API path is not required anymore, as it is not the actual interview used in the map and stats pages.
The `Validation` component is now connected to the global state and gets its interview from there. Changing the interview now calls the `startSetValidateInterview` redux action and the `InterviewSummary` component does not need to load the interview separately.
Whenever the interview is updated by any of the components, it is re-rendered so validation/completion state changes are now visible as they happen.
=> admin: Fix the validation links state when updated

packages/evolution-backend/src/api/survey.user.routes.ts, packages/evolution-frontend/src/actions/Survey.ts, packages/evolution-frontend/src/actions/__tests__/Survey.test.ts, packages/evolution-frontend/src/components/survey/ErrorBoundary.tsx, packages/evolution-frontend/src/components/survey/__tests__/ErrorBoundary.test.tsx, packages/evolution-frontend/src/components/survey/__tests__/__snapshots__/ErrorBoundary.test.tsx.snap, packages/evolution-frontend/src/services/errorManagement/__tests__/errorHandling.test.ts, packages/evolution-frontend/src/services/errorManagement/errorHandling.ts
fixes #704
* Add a server route to receive the exception and interview ID:
`/survey/clientSideException/`. This route logs the error in server
console
* Add an error handling utility function `reportClientSideException`
that sends to the server the error message along with interview ID
* Let the ErrorBoundary call this error handling function when an
exception is caught in a React component. This requires to connect the
boundary component to the global state have access to the current interview
to report the interview ID
* The `handleHttpOtherResponseCode` also calls the exception reporting
function (this function is ill-named and can also be called on
exceptions that are not related to request responses, so the server
needs to be told).
=> survey: Add mechanism to report client side exceptions

packages/evolution-backend/src/api/survey.user.routes.ts, packages/evolution-frontend/src/services/errorManagement/__tests__/errorHandling.test.ts, packages/evolution-frontend/src/services/errorManagement/errorHandling.ts
Add a else clause in the express route in case the exception is not sent
In the frontend, let the exception be of unknown type and handle it properly.
=> errorHandling: Make client-side exception reporting more robust

packages/evolution-backend/src/api/survey.user.routes.ts, packages/evolution-backend/src/services/logging/__tests__/messageLogging.test.ts, packages/evolution-backend/src/services/logging/messageLogging.ts, packages/evolution-frontend/src/components/inputs/maps/google/InputMapGoogle.tsx, packages/evolution-frontend/src/components/survey/ErrorBoundary.tsx, packages/evolution-frontend/src/services/errorManagement/__tests__/errorHandling.test.ts, packages/evolution-frontend/src/services/errorManagement/errorHandling.ts, packages/evolution-legacy/src/components/survey/Survey.js
This uses the `reportClientSideException` callback to report to the server any load error for the map. This adds browser data to the error log.
=> inputMapGoogle: report client side load errors

packages/evolution-frontend/src/components/inputs/maps/google/GoogleGeocoder.tsx
This eliminates the deprecation error on the permanently_closed property that was accessed even if not requested.
=> googleGeocoder: unnest necessary properties only from google place

packages/evolution-common/src/services/odSurvey/__tests__/helpers.test.ts, packages/evolution-common/src/services/odSurvey/helpers.ts
Instead of creating a new Person object that is in no way linked to the interview, if the active person is not defined, or if there are no persons in the household, then `null` is returned.
=> odSurvey: Let `getActivePerson` return `null` if no person found

packages/evolution-common/src/services/odSurvey/types.ts, packages/evolution-frontend/src/services/sections/segments/__tests__/helpers.test.ts, packages/evolution-frontend/src/services/sections/segments/helpers.ts
Add types for loopActivities and simple modes (ie individual/private modes that are often used for many trips).
Add helpers for survey time to check whether a trip is the return trip of a simple single chain, ie origin of first trip is same as the destination of second trip and the mode used is a simple mode. Another helper returns the unique segment of the previous trip of the chain.
Add unit tests for these functions.
=> segments: Add helpers specific to the segment section

packages/evolution-legacy/src/components/survey/Section.js
fixes #740
On Safari on iPhone and iPad, calling the `focus` method on input elements of type radio or checkbox do not focus on those elements, so if they are out of view, the participant may not see that there are invalid widgets.
Since those widget types cannot really "focus" anyway, we simply use the scrollTo position for all widgets except the text boxes, which work on all known platforms.
=> survey: scroll to invalid question instead of trying to focus

.github/workflows/evolution.yml
fixes #748
This step will detect any problem in the admin bundle compilation.
=> Add `yarn build:admin:prod` to the workflow

packages/evolution-frontend/src/components/pages/Survey.tsx
fixes #758
The `startSetInterview` function received in the props receives only 3 parameters that do not include the `History` object. This one is automatically added by the `dispatch` call. This added the History data to the survey instead of the prefilled answers, so we have a lot of un-necessary fields in the interviews.
=> survey: The `startSetInterview` prop type does nto include the `history`

packages/evolution-common/src/services/widgets/WidgetConfig.ts, packages/evolution-generator/src/common/defaultInputBase.tsx, packages/evolution-generator/src/common/validations.tsx, packages/evolution-generator/src/helpers/createConditionals.tsx, packages/evolution-generator/src/types/inputTypes.ts
This makes sure the widget types are as expected and defined in evolution. It removes unused fields in some default inputs for some types.
Tested with generated survey, it may cause compilation errors, easy to fix, on custom widgets.
=> generator: Use types from evolution instead of defining them

example/demo_survey/src/survey/templates/SegmentsSection.tsx, example/demo_survey/src/survey/templates/VisitedPlacesSection.tsx, packages/evolution-frontend/src/actions/Survey.ts, packages/evolution-frontend/src/components/pageParts/Section.tsx, packages/evolution-frontend/src/components/pages/Survey.tsx, packages/evolution-frontend/src/components/survey/GroupWidgets.tsx, packages/evolution-frontend/src/components/survey/Widget.tsx, packages/evolution-frontend/src/components/survey/__tests__/GroupWidgets.test.tsx, packages/evolution-frontend/src/components/survey/__tests__/Widget.test.tsx, packages/evolution-frontend/src/components/survey/__tests__/__snapshots__/Widget.test.tsx.snap, packages/evolution-frontend/src/services/interviews/interview.ts, packages/evolution-legacy/src/components/admin/ValidateSurvey.js
To ensure that widget generation is always handled the same way and new features are not added in a single code path, a `Widget` component is added to display the high level widget (Text, Group, Button, InfoMap or Question). There is one version for end components (`Widget`) and one for widgets that are part of a grouped object (`InGroupWidget`), with additional pathPrefix and different widgetStatus location. 
Section templates in `demo_survey` are updated to use this new component.
Also type the SectionConfig and pass the sectionConfig to the Section widget instead of individual fields. This is a **breaking change** for surveys as section templates will also need to be updated to match the Section's props. See commit message for details.
=> sections: Extract widget component from Section and others

packages/evolution-frontend/src/components/inputs/InputRadioNumber.tsx, packages/evolution-frontend/src/components/inputs/__tests__/InputRadioNumber.test.tsx
fixes #765
The inputRadioNumber is for number data. We should not have to specify a datatype for it to parse the value later, the widget itself should always return a numeric value or `undefined` when reset.
This also adds test for the handleOnChange call to make sure the `onValueChange` is called with the expected values.
=> inputRadioNumber: Make sure the value is always numeric

example/demo_survey/src/admin/parsers/madasare2018.ts, example/demo_survey/src/admin/validations.ts, example/demo_survey/src/routes/admin/admin.routes.ts, example/demo_survey/src/survey/sections.ts, example/demo_survey/src/survey/widgets/householdMembers.tsx, example/demo_survey/tests/test-one-person-helpers.ts, example/demo_survey/tests/test-two-adults-no-trips.UI.spec.ts, locales/en/segments.yml, locales/fr/segments.yml, packages/evolution-frontend/src/components/hooks/__tests__/useSectionTemplate.test.ts, packages/evolution-frontend/src/components/hooks/useSectionTemplate.ts, packages/evolution-frontend/src/services/interviews/interview.ts
* Type the section`preload`'s call and change the second and more arguments to a single named argument, to make it simpler for implementations to use use only the required values without worrying about positioning.
* Fix short mode labels
* Fix UI tests after renaming the `driverLicenseOwnership` widget.
=> Type the section `preload`'s call and other fixes

packages/evolution-backend/src/models/__tests__/interviews.db.test.ts, packages/evolution-backend/src/models/interviews.db.queries.ts, packages/evolution-backend/src/services/adminExport/exportAllToCsvByObject.ts, packages/evolution-common/src/services/interviews/interview.ts, packages/evolution-frontend/src/components/admin/interviews/InterviewSearchList.tsx, packages/evolution-frontend/src/components/admin/interviews/InterviewsCreateLink.tsx
Add the `includeInterviewerData` option to the interviews stream query. If set to `true`, it will return whether the interview was created by an interviewer and the number of interviewer who touched this interview.
This adds the `_interviewer_count` and `_interviewer_created` columns to
the exported interviews' csv file.
Also add the project shortname to the exported file names.
=> Admin export: Add interviewer count and created to exported interview csv file

example/demo_survey/src/survey/widgets/segments.tsx, locales/en/segments.yml, locales/fr/segments.yml, packages/evolution-common/src/services/sections/segments/__tests__/groupSegments.test.ts, packages/evolution-common/src/services/sections/segments/groupSegments.ts, packages/evolution-common/src/services/widgets/WidgetConfig.ts, packages/evolution-frontend/src/components/survey/GroupWidgets.tsx
This group is the main group for the `segments` object of the survey. It contains the button labels, as well as the segment widgets.
The demo_survey now uses this group widget instead of the main one.
TODO The group or its widgets is not yet configurable
=> segments: add a group widget for the segments

packages/evolution-frontend/src/components/inputs/InputRadioNumber.tsx, packages/evolution-frontend/src/components/inputs/__tests__/InputRadioNumber.test.tsx
Fixes #781
The `Specify` widget should only be shown if the value is set and it is above the max.
=> inputRadioNumber: Fix check when value is 0 and resolves to `false`

example/demo_survey/src/survey/widgets/segments.tsx, locales/en/segments.yml, locales/fr/segments.yml, packages/evolution-common/src/services/odSurvey/__tests__/helpers.test.ts, packages/evolution-common/src/services/odSurvey/helpers.ts, packages/evolution-common/src/services/sections/segments/__tests__/buttonSaveTripSegments.test.ts, packages/evolution-common/src/services/sections/segments/__tests__/groupPersonTrips.test.ts, packages/evolution-common/src/services/sections/segments/__tests__/groupSegments.test.ts, packages/evolution-common/src/services/sections/segments/__tests__/widgetTripSegmentsIntro.test.ts, packages/evolution-common/src/services/sections/segments/buttonSaveTripSegments.ts, packages/evolution-common/src/services/sections/segments/groupPersonTrips.ts, packages/evolution-common/src/services/sections/segments/groupSegments.ts, packages/evolution-common/src/services/sections/segments/widgetTripSegmentsIntro.ts, packages/evolution-common/src/services/widgets/WidgetConfig.ts, packages/evolution-common/src/utils/helpers.ts, packages/evolution-frontend/src/services/display/__tests__/frontendHelper.test.ts, packages/evolution-frontend/src/services/display/frontendHelper.ts, packages/evolution-legacy/src/helpers/survey/survey.js
As part of the "15-minutes survey" segment section configuration, the personTrips group and the widgets it contains are moved to evolution and unit tested.
They are also used in demo_survey.
The widgets content was taken and adapted from the od_nationale_2024 survey when it was different from the demo_survey widgets. They are mostly taken as is, with FIXMEs where additional configuration, or some thought, would be required.
=> trips: move necessary widgets and helper functions for the trips group

example/demo_survey/package.json
We reduce the memory limit of the build:prod and build:admin:prod step by setting --max_old_space_size=1024
This step can be memory intensive, and if you attempt to start multiple survey at the same time on a machine you can quickly run out of memory.
The change does not have a significant impact on the run time of the build step
=> Reduce memory limit for build:prod step

locales/en/menu.json, locales/fr/menu.json, packages/evolution-frontend/src/components/pageParts/SectionNav.tsx
This is a dangerous feature that can erase an interview data and should not be available for any reason. If the feature should at any point come back, it should be documented and implemented correctlyt o avoid mistakes with production data.
=> admin: Drop the "reset interview" features

packages/evolution-backend/src/services/adminExport/__tests__/exportAllToCsvByObject.test.ts, packages/evolution-backend/src/services/adminExport/exportAllToCsvByObject.ts
fixes #809
To avoid simple paths being added to an object file because they have the same prefix (for example `household.personsDidSomething` in the `household_persons` file, we look for the object path with a '.' (eg. `household.persons.` in the path.
Also add unit tests for the exportAllToCsvByObject export and fix array of objects being exported as en empty field with the root object.
Add comments in some places as necessary and remove the `arrayPaths` field as it is not used or necessary.
=> objects to csv export: check for the dotted object path

example/demo_survey/src/survey/sections.ts, locales/en/segments.yml, locales/fr/segments.yml, packages/evolution-common/src/services/questionnaire/sections/segments/__tests__/sectionSegment.test.ts, packages/evolution-common/src/services/questionnaire/sections/segments/sectionSegments.ts, packages/evolution-generator/src/skeleton/template.tsx
Task 6 of #501
This moves the segment section configuration as is to evolution-common.
The demo_survey is updated to use this section configuration
Add unit tests for the `preload` and other functions of the section.
The section is not entirely configurable yet, it is just the current configuration moved to evolution. There are a lot of FIXMEs in the code. There is still a missing layer between the configurable section and the actual questionnaire configuration.
=> segments: Move the segment section configuration in evolution

packages/evolution-frontend/src/actions/utils/Conditional.ts, packages/evolution-frontend/src/actions/utils/WidgetOperation.ts, packages/evolution-frontend/src/actions/utils/__tests__/Conditional.test.ts, packages/evolution-frontend/src/actions/utils/__tests__/WidgetOperation.test.ts, packages/evolution-frontend/src/components/survey/GroupWidgets.tsx
The conditional function received in the `checkConditional` function is indeed
a `ParsingFunction`, as defined in the `WidgetConfig` type. This
function does not expect a customPath as third parameter, but a user, so
we fix the call parameters. Also, the calls of the `checkConditional`
effectively send the `user` parameter, which was not the case before.
Also
Update comments and test names for choice conditional
This confirms the fix #55
=> conditional: type and clean the Conditional file

packages/evolution-frontend/src/actions/Survey.ts, packages/evolution-frontend/src/actions/__tests__/Survey.test.ts, packages/evolution-frontend/src/actions/utils/WidgetOperation.ts, packages/evolution-frontend/src/actions/utils/__tests__/WidgetOperation.test.ts
See individual commits for more details:
Add unit tests with the customPath
Rename the `prepareWidgets` to `prepareSectionWidgets`
Change the return type of the `prepareSectionWidgets` function to return an object instead of array of various data (that were wrongly used anyway)
=> More housekeeping around the WidgetOperation file

packages/evolution-legacy/src/styles/survey/_admin.scss, packages/evolution-legacy/src/styles/survey/_header.scss
fix: #574 fix: #448
Fix title header overflow
Make header H1 show big on big screen and small on small screen so the header doesn't break
Remove the user name for survey but show on admin
fixes #574 fixes #448
=> Frontend: Fix title header overflow

packages/evolution-backend/jest.config.js, packages/evolution-backend/jest.sequential.config.js, packages/evolution-backend/src/api/admin.routes.ts, packages/evolution-backend/src/api/admin/exports.routes.ts, packages/evolution-backend/src/api/express-session.d.ts, packages/evolution-backend/src/api/survey.validation.routes.ts, packages/evolution-backend/src/models/interviews.db.queries.ts, packages/evolution-backend/src/models/migrations/20230921100001_setInterviewSurvey.ts, packages/evolution-backend/src/models/participants.db.queries.ts, packages/evolution-backend/src/services/accessCode.ts, packages/evolution-backend/src/services/adminExport/exportAllToCsvByObject.ts, packages/evolution-backend/src/services/adminExport/types.ts, packages/evolution-backend/src/services/auth/roleDefinition.ts, packages/evolution-backend/src/services/interviews/interviews.ts, packages/evolution-backend/src/services/routing/types.ts, packages/evolution-backend/src/services/validations/serverValidation.ts, packages/evolution-backend/src/tasks/exportInterviewsJson.task.ts
The lint warnings from evolution-backend (other than "unexpected any") have been removed.
22 warnings got removed (55 to 33).
=> Remove Lint warnings from evolution-backend

packages/evolution-common/src/utils/__tests__/helpers.test.ts, packages/evolution-common/src/utils/helpers.ts
Because the type of null is considered an object in javascript, the function would then try to read one of its properties, throwing an error. Also adds a test to make sure the bug is not reproduced.
=> Fix bug where parsing null value with type geojson would throw an error.

packages/evolution-common/jest.config.js, packages/evolution-common/src/services/baseObjects/BaseOrganization.ts, packages/evolution-common/src/services/baseObjects/BaseSegment.ts, packages/evolution-common/src/services/baseObjects/BaseVehicle.ts, packages/evolution-common/src/services/baseObjects/Trip.ts, packages/evolution-common/src/services/baseObjects/VisitedPlace.ts, packages/evolution-common/src/services/baseObjects/attributeTypes/TripChainAttributes.ts, packages/evolution-common/src/services/baseObjects/interview/InterviewParadata.ts, packages/evolution-common/src/services/odSurvey/helpers.ts, packages/evolution-common/src/services/questionnaire/sections/common/widgetsSwitchPerson.ts, packages/evolution-common/src/services/questionnaire/sections/segments/groupPersonTrips.ts, packages/evolution-common/src/services/questionnaire/sections/segments/groupSegments.ts, packages/evolution-common/src/services/questionnaire/sections/segments/sectionSegments.ts, packages/evolution-common/src/services/questionnaire/sections/segments/widgetPersonTripsTitle.ts, packages/evolution-common/src/services/questionnaire/sections/segments/widgetSameAsReverseTrip.ts, packages/evolution-common/src/services/questionnaire/sections/segments/widgetSegmentHasNextMode.ts, packages/evolution-common/src/services/questionnaire/sections/segments/widgetSegmentModePre.ts, packages/evolution-common/src/services/questionnaire/sections/segments/widgetTripSegmentsIntro.ts
The lint warnings from evolution-common (other than "unexpected any") have been removed.
26 warnings got removed (104 to 78).
=> Remove Lint warnings from evolution-common

packages/evolution-interviewer/jest.config.js, packages/evolution-interviewer/jest.sequential.config.js, packages/evolution-interviewer/src/client/components/monitoring/RefreshInterviewerCache.tsx, packages/evolution-interviewer/src/server/routes/interviewer.routes.ts
The lint warnings from evolution-interviewer (other than "unexpected any") have been removed.
7 warnings got removed (18 to 11).
=> Remove Lint warnings from evolution-interviewer

packages/evolution-legacy/src/styles/survey/_admin.scss, packages/evolution-legacy/src/styles/survey/_header.scss
It's a cherry-pick from c41dbac13ca2daad8c5d3fbd5804d8adbe1e6049 of the main.
Make header H1 show big on big screen and small on small screen so the header doesn't break Remove the user name for survey but show on admin
fixes #574 fixes #448
=> Fix title header overflow

example/demo_survey/tests/test-input-validation.UI.spec.ts, example/demo_survey/tests/test-navigation-bar.UI.spec.ts, example/demo_survey/tests/test-one-person-no-trips.UI.spec.ts, example/demo_survey/tests/test-two-adults-no-trips.UI.spec.ts
A recent commit removed by default the username in the header for the participant app. UI tests were failing as it looked for the name.
=> tests: fix UI tests with anonym user hidden

example/demo_survey/config.js, example/demo_survey/webpack.admin.config.js, packages/evolution-legacy/src/apps/admin/server/index.js
commit 40bea0acf8ab6d4128d5696a56a82ce4a1545f39 removed the localLogin from the demo_survey application. But that configuration was used for the admin application.
A new configuration option, `adminAuth`, can be used to configure the admin login configuration. In webpack and in the server initialization, the `adminAuth` replaces the `auth` option of the configuration.
=> auth: fix admin auth configuration

packages/evolution-frontend/src/actions/utils/WidgetOperation.ts, packages/evolution-frontend/src/actions/utils/__tests__/WidgetOperation.test.ts
The unit tests are complex enough as it is and were using some globally defined variable, so it was hard to follow what was being done. Now tests each control the values that they use and more comments are added above each code block.
Tests are renamed to actually represent what they do, as there was confusion between validation and conditionals.
Also, each test now calls the `prepareSectionWidgets` function once, but rather set their previous status instead of relying on a previous call to set the statuses.
=> widgetOperation: Refactor and document unit tests

packages/evolution-backend/src/api/helpers/__tests__/validateUuidMiddleware.test.ts, packages/evolution-backend/src/api/helpers/validateUuidMiddleware.ts, packages/evolution-backend/src/api/survey.user.routes.ts, packages/evolution-backend/src/api/survey.validation.routes.ts
If the interviewUuid received is of a bad format, the logging middleware and the query itself will throw exceptions about the format. We add a proper middleware to validate the interview UUID format before those calls and return a `400` bad request response to the client instead of server error.
This middleware is used in validation and user routes that have a uuid parameter.
Add unit tests for this middleware
=> api: add express middleware to validate uuid format

packages/evolution-frontend/src/actions/Survey.ts
This makes sure all code path decrement the loading state, without repeating it at every necessary place. All code paths have been tested and there is no side-effect. The only difference is that if there is no call to the server to make, the callback is now run before decrementing the state instead of after, which may have been a mistake in the first place as the call to the `callback` is done before decrementing the loading state in the other code path.
=> survey: decrement the loading state in a finally block

example/demo_survey/src/server.ts, packages/evolution-backend/package.json, packages/evolution-backend/src/apps/participant/index.ts, packages/evolution-backend/src/apps/participant/serverApp.ts
** BREAKING CHANGE **
Survey's server entry file now need to import the server app function from evolution-backend instead of legacy. For example:
```
import setupServer from 'evolution-backend/lib/apps/participant';
```
=> app: move the participant server app to evolution-backend

.github/workflows/build-docker-image.yml, .github/workflows/test-docker-build.yml
First workflow will test docker build on each PR
Second will build the docker image and push to both docker hub and github package repo
(This have been applied to trRouting and transition so far)
=> Add github workflow to build docker images

locales/en/auth.json, locales/fr/auth.json, packages/evolution-frontend/src/components/pages/auth/AuthPage.tsx
fixes #861
In the `AuthPage` component, the authMethods considered for the page are
only those whose value is not `false`. This will make sure that the
`passwordless` box is not shown if the `passwordless` value is `false`
and avoids having to make those checks later in the component children.
Also
auth: remove references to `connectWithGoogle` and `connectWithFacebook`
=> authPage: do not consider auth methods set to `false`

README.md
fix: https://github.com/chairemobilite/evolution/issues/871
The command has recently been changed to `yarn test:ui` to run the playwright tests, in coherence with most of the surveys and to make it clearer that it is UI tests.
=> doc: update Readme with correct instructions to run UI tests

.github/workflows/ui-test.yml
New github workflow that runs the playwright ui tests. Based on the main CI one, without the lint/unit-test/etc.
Start a postgresql DB to be able to run the application.
We only run on commit to have access to the Google Key secret
Extracted and adapted from PR #682
=> Add UI Test run on CI

.github/workflows/build-docker-image.yml
We don't want it to run on people's forks
=> Restrict the build docker workflow to run only on the official repo

example/demo_survey/config.js, example/demo_survey/src/survey/widgets.ts, example/demo_survey/tests/test-one-person-helpers.ts, locales/en/survey.yml, locales/fr/survey.yml, packages/evolution-frontend/src/components/pageParts/Section.tsx, packages/evolution-frontend/src/components/pageParts/SectionProgressBar.tsx, packages/evolution-frontend/src/services/display/__tests__/frontendHelper.test.ts, packages/evolution-frontend/src/services/display/frontendHelper.ts, packages/evolution-frontend/src/styles/survey/_survey.scss, packages/evolution-frontend/tests/ui-testing/testHelpers.ts, packages/evolution-generator/src/scripts/generate_UI_tests.py
Fix: #555 
Add a SectionProgressBar in the Section page. 
Calculate and save the survey completion percentage when clicking on the 'Save and Continue' button.
Put the survey completion inside a circular-progress.
Only show SectionProgressBar if the config is hasSectionProgressBar for each section.
Add a sectionProgressBarTest UI test. Add these tests to the demo_survey.
Also generate the sectionProgressBarTest inside the UI template tests.
Format _survey.scss.
Format frontendHelper.test.ts and a responses._completionPercentage inside validateButtonActionWithCompleteSection
=> Add a SectionProgressBar in the Section page.

example/demo_survey/tests/test-one-person-helpers.ts, example/demo_survey/tests/test-one-person-no-trips.UI.spec.ts, packages/evolution-common/src/utils/helpers.ts, packages/evolution-frontend/src/components/pageParts/Section.tsx, packages/evolution-frontend/src/components/pageParts/SectionProgressBar.tsx, packages/evolution-frontend/src/services/display/frontendHelper.ts, packages/evolution-frontend/src/styles/survey/_survey.scss, packages/evolution-generator/src/scripts/generate_section_configs.py
Fix bug with SectionProgressBar
The section completion percentage will now start at 0% when the first section begins and will reach 100% once the last section is initiated.
To achieve this, we will disregard completed sections when calculating the total number of sections.
Test the completed page and the section progress bar in the demo survey.
Move the circular progress at the end.
Move the circular progress at the end of the div so the user will read the title more easily and only focus on the completion rate if needed.  
Generate the title when possible.
We identified a bug that prevented the section title from displaying when the section was not included in the navigation.
To resolve this issue, we will generate the title whenever possible.
Update sectionTarget parameter to use more …
=> Fix bug with SectionProgressBar

.github/workflows/evolution.yml, example/demo_survey/config.js, example/demo_survey/src/survey/widgets.ts, example/demo_survey/tests/test-one-person-helpers.ts, example/demo_survey/tests/test-one-person-no-trips.UI.spec.ts, locales/en/survey.yml, locales/fr/survey.yml, packages/evolution-common/src/utils/helpers.ts, packages/evolution-frontend/src/components/pageParts/Section.tsx, packages/evolution-frontend/src/components/pageParts/SectionProgressBar.tsx, packages/evolution-frontend/src/services/display/__tests__/frontendHelper.test.ts, packages/evolution-frontend/src/services/display/frontendHelper.ts, packages/evolution-frontend/tests/ui-testing/testHelpers.ts, packages/evolution-generator/src/scripts/generate_UI_tests.py, packages/evolution-generator/src/scripts/generate_section_configs.py, packages/evolution-legacy/src/styles/survey/_survey.scss
Calculate and save the survey completion percentage when clicking on the 'Save and Continue' button. Put the survey completion inside a circular-progress. Only show SectionProgressBar if the config is hasSectionProgressBar for each section. Add a sectionProgressBarTest UI test. Add these tests to the demo_survey. Also generate the sectionProgressBarTest inside the UI template tests. Format _survey.scss.
Format frontendHelper.test.ts and a responses._completionPercentage inside validateButtonActionWithCompleteSection
Cherry-pick of a314ff3
Run test on 0.3.0 branch 
Enable the basic workflow for the 0.3.0 branch
Cherry-pick from 3e0fcf2
Add the VisitedPlace type and _cloneDeep function in this commit, to fix compilation problems.
The section completion percentage will now start at 0% when …
=> Add a SectionProgressBar in the Section page. (#907)

packages/evolution-common/src/services/questionnaire/types/Data.ts, packages/evolution-common/src/tests/surveys/testCasesInterview.ts, packages/evolution-frontend/src/actions/LoadingState.ts, packages/evolution-frontend/src/actions/Survey.ts, packages/evolution-frontend/src/actions/SurveyAdmin.ts, packages/evolution-frontend/src/components/admin/pages/ValidateSurvey.tsx, packages/evolution-frontend/src/components/admin/pages/ValidationPage.tsx, packages/evolution-frontend/src/components/admin/validations/InterviewSummary.tsx, packages/evolution-frontend/src/components/admin/validations/ValidationCommentForm.tsx, packages/evolution-frontend/src/components/admin/validations/ValidationOnePageSummary.tsx, packages/evolution-frontend/src/components/pages/Survey.tsx, packages/evolution-frontend/src/components/survey/Button.tsx, packages/evolution-frontend/src/services/errorManagement/errorHandling.ts, packages/evolution-frontend/src/store/survey/__tests__/reducer.test.ts, packages/evolution-frontend/src/store/survey/types.ts
This makes sure all redux actions are properly typed in their signature, but also in the callers. This will simplify their modification by forcing compilation errors.
See individual commits for more details
fixes #892
=> Type redux actions

example/demo_survey/references/questionnaire_list_en.txt, example/demo_survey/references/questionnaire_list_fr.txt, locales/en/admin.json, locales/fr/admin.json, packages/evolution-backend/src/api/admin/__tests__/exports.routes.test.ts, packages/evolution-backend/src/api/admin/__tests__/questionnaire_list_en.txt, packages/evolution-backend/src/api/admin/__tests__/questionnaire_list_fr.txt, packages/evolution-backend/src/api/admin/exports.routes.ts, packages/evolution-frontend/src/components/admin/pages/ExportInterviewData.tsx
fix: #650 
Admin: Download survey questionnaire list Text file
Add a new admin data route to download questionnaire list text file in many languages.
Handle possible errors with this new admin data route.
Align to the left all export button, because it's easier to readed.
Put an example file in French and English for questionnaire_list. Normally we generated this with Evolution-Generator.
Add unit tests for the new admin data route, mock some functions to make it works.
Fix some errors messages on ExportInterviewData.tsx: it will now show the localizedMessage.
=> Admin: Download survey questionnaire list Text file

.gitignore, package.json, packages/evolution-common/jsdoc.json, packages/evolution-common/package.json, packages/evolution-common/src/services/geodata/SurveyGeographyUtils.ts, packages/evolution-common/src/services/odSurvey/helpers.ts, packages/evolution-common/src/services/questionnaire/sections/common/buttonValidateAndGotoNextSection.ts, packages/evolution-common/src/services/questionnaire/types/Data.ts, packages/evolution-common/src/utils/helpers.ts
fixes #591
Add yarn scripts to generate documentation for the `evolution-common` javascript code.
Make sure there are no empty returns on JsDoc, otherwise 'yarn jsdoc' won't work.
Use @typedef to identify a type that will be used directly inside JsDoc.
Ignore the api/docs folder inside Git.
TODO
* Document the typescript code instead, so that the types are also documented
* Document all the evolution packages, not just `common`
* Provide a higher level "glue" to document high level concepts that can then link to the jsdoc complete documentation of the packages.
To use this commit, you need to install `jsdoc` globally on your system with
`npm i -g jsdoc`
=> Add scripts to produce documentation using jsdoc

.gitignore, README.md, packages/evolution-common/jsdoc.json
Fix: #923 
JsDoc Documentation: Generate and View API Documentation with JSDoc 
Note: Currently, the JSDoc documentation only covers the `Evolution-Common` package. Some functions are still missing JSDoc comments, so the documentation may not be complete.
For more details about JSDoc, visit the [official documentation](https://jsdoc.app/).
To install JSDoc globally, run the following command: npm i -g jsdoc
To generate the API documentation, use the following command: yarn jsdoc This will create the documentation in the `docs/api` folder.
To view the generated HTML documentation, you can use an extension like **Live Server** in Visual Studio Code. Follow these steps:
1. Install the **Live Server** extension from the VS Code marketplace.
2. Open the `docs/api` folder in VS Code.
3. …
=> Generate and View API Documentation with JSDoc

example/demo_survey/src/survey/sections.ts, example/demo_survey/src/survey/templates/VisitedPlacesSection.tsx, example/demo_survey/src/survey/widgets/householdMembers.tsx, example/demo_survey/src/survey/widgets/visitedPlaces.tsx, packages/evolution-common/src/services/questionnaire/sections/common/__tests__/widgetsSwitchPerson.test.ts, packages/evolution-common/src/services/questionnaire/sections/common/widgetsSwitchPerson.ts, packages/evolution-common/src/services/questionnaire/sections/segments/__tests__/buttonSaveTripSegments.test.ts, packages/evolution-common/src/services/questionnaire/sections/segments/__tests__/sectionSegment.test.ts, packages/evolution-common/src/services/questionnaire/sections/segments/buttonSaveTripSegments.ts, packages/evolution-common/src/services/questionnaire/sections/segments/sectionSegments.ts, packages/evolution-common/src/services/questionnaire/types/Data.ts, packages/evolution-frontend/src/actions/Survey.ts, packages/evolution-frontend/src/actions/SurveyAdmin.ts, packages/evolution-frontend/src/actions/__tests__/Survey.test.ts, packages/evolution-frontend/src/components/admin/pages/ValidateSurvey.tsx, packages/evolution-frontend/src/components/admin/validations/InterviewStats.tsx, packages/evolution-frontend/src/components/admin/validations/InterviewSummary.tsx, packages/evolution-frontend/src/components/admin/validations/ValidationCommentForm.tsx, packages/evolution-frontend/src/components/admin/validations/ValidationOnePageSummary.tsx, packages/evolution-frontend/src/components/pages/Survey.tsx, packages/evolution-frontend/src/components/survey/Question.tsx, packages/evolution-frontend/src/components/survey/sectionTemplates/TripsAndSegmentsSection.tsx, packages/evolution-frontend/src/components/survey/sectionTemplates/__tests__/TripsAndSegmentsSection.test.tsx, packages/evolution-frontend/src/services/display/__tests__/frontendHelper.test.ts, packages/evolution-frontend/src/services/display/frontendHelper.ts
The second parameter of the `StartUpdateInterview` function type is not a `data` parameter with typed arguments. The `valuesByPath`, `unsetPaths`, interview` and `gotoFunction` are placed in this argument, to more easily allow for undefined parameters and add eventual new parameters to this call.
The `callback` function is now the third optional parameter of the call.
Update all usages of this call.
=> StartUpdateInterview: use named argument instead of positional

packages/evolution-frontend/src/components/inputs/InputSelect.tsx
fixes #901
The `React.Fragment` needed a key for the group with the disabled element. Also, add the group and value indexes to keys to make sure they all have unique names.
=> inputSelect: Add missing key in `React.Fragment` child

yarn.lock
Delete all @babel/* package entries from `yarn.lock` and run `yarn` again.
fixes #887
=> dep: Upgrade dependencies of @babel/* packages

example/demo_generator/package.json, example/demo_survey/package.json, packages/evolution-backend/package.json, packages/evolution-common/package.json, packages/evolution-frontend/package.json, packages/evolution-interviewer/package.json, yarn.lock
Using npm's `depcheck` module, validate that all packages in the `package.json` are used and put in the right `dependencies` or `devDependencies` section.
=> dep: remove un-used dependencies and put them in the right place

.github/workflows/evolution-generator.yml, .gitignore, packages/evolution-generator/poetry.lock, packages/evolution-generator/pyproject.toml, packages/evolution-generator/src/helpers/generator_helpers.py, packages/evolution-generator/src/scripts/generate_choices.py, packages/evolution-generator/src/tests/references/.gitignore, packages/evolution-generator/src/tests/survey/common/.gitignore, packages/evolution-generator/src/tests/test_generate_choices.py, packages/evolution-generator/src/tests/test_generate_input_range.py
Fix Python tests for Evolution-Generator 
Update the path of all the tests from an old structure version to the new structure.
Fix all the tests, some of the error messages have been changed since the last time we tested.
Ignore some of the generated output and input of these tests.
Install pytest package in Poetry.
Run Python unit tests inside the Evolution-Generator worflows
I did add some .gitignore file because we need an empty folder to save the generated files from the tests.
=> Fix poetry unit test and add to worflows

packages/evolution-backend/src/models/__tests__/participants.db.test.ts, packages/evolution-backend/src/models/migrations/20250526083900_createLoginLogTable.ts, packages/evolution-backend/src/models/participants.db.queries.ts, packages/evolution-backend/src/services/auth/__tests__/participantAuthModel.test.ts, packages/evolution-backend/src/services/auth/participantAuthModel.ts
fixes #932
Add a database table `sv_participants_logins` that tracks the participant logins in the survey. This table simply links a `participant_id` with the timestamp of the login.
Implement the `recordLogin` method in the `ParticipantModel` class to save the login timestamp in the participants' login table.
=> auth: record participant login in the interview

packages/evolution-backend/src/api/__tests__/survey.participant.routes.test.ts, packages/evolution-backend/src/api/__tests__/survey.user.routes.test.ts, packages/evolution-backend/src/api/survey.common.routes.ts, packages/evolution-backend/src/api/survey.participant.routes.ts, packages/evolution-backend/src/api/survey.user.routes.ts, packages/evolution-backend/src/services/interviews/interviews.ts, packages/evolution-frontend/src/actions/Survey.ts, packages/evolution-frontend/src/actions/__tests__/Survey.test.ts
The `startCreateInterview` and `startSetInterview` redux actions had a lot of code in common. Instead of duplicating them, we let the server create the interview in the `activeInterview` route of the participant app (a 404 is returned in the case of an unexisting interview in the interviewer app).
Since the function in the common routes does not have a lot to do anymore, each version of the caller route now does its own code, instead.
Add unit tests for the participant and user `activeInterview` routes.
=> survey: merge interview create and activation for participants

.env.example, example/demo_survey/config.js, locales/en/server.json, locales/en/survey.yml, locales/fr/server.json, locales/fr/survey.yml, packages/evolution-backend/src/api/__tests__/survey.participant.routes.test.ts, packages/evolution-backend/src/api/survey.participant.routes.ts, packages/evolution-backend/src/apps/participant/routes.ts, packages/evolution-backend/src/services/logging/__tests__/supportRequest.test.ts, packages/evolution-backend/src/services/logging/supportRequest.ts, packages/evolution-common/src/config/project.config.ts, packages/evolution-frontend/src/components/pageParts/FloatingSupportForm.tsx, packages/evolution-frontend/src/components/pageParts/SupportForm.tsx, packages/evolution-frontend/src/components/routers/ParticipantSurveyRouter.tsx, packages/evolution-frontend/src/styles/survey/_floating-support.scss, packages/evolution-frontend/src/styles/survey/styles-participant-survey.scss
fixes #906
This form is present on every page of the participant app. A button at the bottom right corner with the text "Need help?" can be clicked by the participant. It opens a simple form where the user can enter his email address and a message explaining the support request. The support request will contain the URL of the current page the participant is on.
Upon submission, this forms sends the message to the backend, which then sends an email to the addresses specified by the `SUPPORT_REQUEST_EMAIL` environment variable. This environment variable has the following format: `lang:comma-separated-emails;lang:comme-separated-emails` to specify the emails to send the support requests to, as well as the language that those recipients want the email.
The subject of the support request …
=> survey: add a support form to the participant app

packages/evolution-common/src/services/questionnaire/types/WidgetConfig.ts, packages/evolution-common/src/services/questionnaire/types/__tests__/WidgetConfig.test.ts, packages/evolution-common/src/utils/__tests__/helpers.test.ts, packages/evolution-common/src/utils/helpers.ts, packages/evolution-frontend/src/actions/utils/WidgetOperation.ts, packages/evolution-frontend/src/components/survey/Question.tsx
fixes #1036
Add a `asArray` parameter to the `parseValue` function, which allows to specify if the expected value should be an array, but still convert to the correct datatype the values in the array.
Add a `isInputTypeWithArrayValue` function to determine if the input type should give an array value. checkboxes and multiselects are inputs with array values.
=> inputs: let the checkbox and multiselect parse arrays

packages/evolution-common/src/services/questionnaire/sections/NavigationService.ts, packages/evolution-common/src/services/questionnaire/sections/__tests__/NavigationService.test.ts, packages/evolution-common/src/services/questionnaire/types/Data.ts, packages/evolution-common/src/services/questionnaire/types/SectionConfig.ts, packages/evolution-common/src/services/questionnaire/types/__tests__/SectionConfig.test.ts, packages/evolution-frontend/src/actions/Survey.ts, packages/evolution-frontend/src/components/admin/pages/SurveyCorrection.tsx, packages/evolution-frontend/src/components/hoc/__tests__/WithSurveyContextHoc.test.tsx, packages/evolution-frontend/src/components/pages/SurveyParticipant.tsx
fixes #1027
Each user-defined functions in the `SectionConfig` type is wrapped
around a try/catch, which allows to give a complete message on which
function/section the error occurred in. The error is thrown and should
be caught by the survey's catchAll mechanism and send to the server.
=> navigation: catch errors on section config's functions

packages/evolution-common/src/services/questionnaire/sections/NavigationService.ts, packages/evolution-common/src/services/questionnaire/sections/__tests__/NavigationService.test.ts
fixes #1064
Add a unit test which shows the problem of the extra element in the iteration blocks during navigation.
Set the `objectIds` to the random order when getting the iteration contexts instead of replacing in the array directly.
=> navigation: fix random order list when already assigned

example/demo_survey/config.js, locales/en/auth.json, locales/en/survey.yml, locales/fr/auth.json, locales/fr/survey.yml, packages/evolution-backend/src/api/__tests__/auth.routes.test.ts, packages/evolution-backend/src/api/__tests__/survey.participant.routes.test.ts, packages/evolution-backend/src/api/auth.routes.ts, packages/evolution-backend/src/api/express-session.d.ts, packages/evolution-backend/src/api/survey.participant.routes.ts, packages/evolution-frontend/src/actions/Auth.ts, packages/evolution-frontend/src/components/pageParts/SupportForm.tsx, packages/evolution-frontend/src/components/pages/auth/ByFieldLoginForm.tsx, packages/evolution-frontend/tests/ui-testing/testHelpers.ts, yarn.lock
fixes #1021
The support form always provides a captcha. As for `byField` login form,
it will display a captcha after the first un-successful login attempts.
The backend route for support and byField login have been updated to use
the captcha validation middleware.
Also update Evolution
=> survey: support captcha in support form and byField

packages/evolution-generator/src/scripts/generate_labels.py, packages/evolution-generator/src/scripts/generate_widgets.py, packages/evolution-generator/src/tests/test_generate_widgets.py
fixes #1105
If there is no context, or the requested context does not exist, there should always be a fallback translation string to avoid untranslated text. The `other` gender should be this default one.
=> generator: make the `other` gender translation the default
