chairemobilite/evolution

packages/evolution-backend/src/models/migrations/20230427142000_setInterviewParticipant.ts
packages/evolution-legacy/src/apps/admin/server/serverApp.js
packages/evolution-legacy/src/apps/participant/server/serverApp.js

And move the authentication routes initialization before setting other routes, as passport needs to be initialized first.

Update to latest Transition

---

README.md

Also add instructions for updating the repository.

Update the README for the `git submodule` command

---

packages/evolution-backend/src/models/migrations/20230509100000_updateInterviewIndexes.ts
packages/evolution-common/src/services/widgets/WidgetConfig.ts
packages/evolution-frontend/src/actions/utils/WidgetOperation.ts
packages/evolution-frontend/src/actions/utils/__tests__/WidgetOperation.test.ts

Interpolate path for any widget type if path is string

---

example/demo_survey/src/survey/widgets/home.tsx
packages/evolution-common/src/services/widgets/WidgetConfig.ts
packages/evolution-frontend/src/components/inputs/InputString.tsx
packages/evolution-frontend/src/components/inputs/__tests__/InputString.test.tsx
packages/evolution-frontend/src/components/inputs/__tests__/__snapshots__/InputString.test.tsx.snap

Implements necessary features to fix issue https://github.com/chairemobilite/od_mtl_2023/issues/400
Thanks!

Allow forcing string input to be lowercase or uppercase

---

packages/evolution-frontend/package.json
packages/evolution-frontend/src/components/inputs/InputCheckbox.tsx
packages/evolution-frontend/src/components/inputs/InputRadio.tsx
packages/evolution-frontend/src/components/inputs/__tests__/InputCheckbox.test.tsx
packages/evolution-frontend/src/components/inputs/__tests__/InputRadio.test.tsx
packages/evolution-frontend/src/components/inputs/__tests__/__snapshots__/InputCheckbox.test.tsx.snap
packages/evolution-frontend/src/components/inputs/__tests__/__snapshots__/InputRadio.test.tsx.snap
yarn.lock

Related issue : https://github.com/chairemobilite/evolution/issues/95

feat(InputCheckbox+InputRadio) : htmlHandling

---

scripts/README.md
scripts/fillLocales.py

Add a directory named `scripts` that may contain helper scripts for survey development.
Add the `fillLocales.py` scripts, which takes a `csv` file and creates/updates the `yml` locales files. Add to README to explain how to use this script.

Add the fillLocales.py script to get locales strings from csv

---

example/demo_survey/locales/en/survey.json
example/demo_survey/locales/fr/survey.json
locales/en/main.json
locales/fr/main.json
packages/evolution-legacy/src/components/survey/Survey.js

The footer will be populated using the contents of the `survey:footer` translatable key
**TODO**: Make it so that the footer sticks to the bottom of the page. My CSS skills are not good enough for this and I will focus on more pressing issues instead

Add a footer to a survey page

---

README.md

Mettre à jour le ReadMe d'Évolution pour Windows.

docs: mettre à jour le readMe d'évolution pour windows

---

packages/evolution-frontend/src/components/inputs/InputMapFindPlace.tsx

Required to fix issue https://github.com/chairemobilite/od_mtl_2023/issues/626

Update map zoom and pan if InputMapFindPlace is given an initial value

---

packages/evolution-common/src/utils/__tests__/helpers.test.ts
packages/evolution-common/src/utils/helpers.ts

Check a string against a regex to verify it is a valid phone number.

Add Phone number validation util.

---

packages/evolution-legacy/src/components/survey/Button.js

button: remove the extra brackets in isDisabled

---

packages/evolution-common/src/services/interviews/interview.ts
packages/evolution-common/src/utils/__tests__/helpers.test.ts
packages/evolution-common/src/utils/helpers.ts
packages/evolution-legacy/src/helpers/survey/helper.js
yarn.lock

@kaligrafy This should fix part of https://github.com/chairemobilite/od_mtl_2023/issues/796 the one causing the worst problems.
Please make sure it's acceptable in evolution. I tested with demo_survey and it works.

Replace places by original before deleting place used as shortcut

---

scripts/fillLocales.py

Fixes https://github.com/chairemobilite/evolution/issues/190

Script: Update fill locales for Windows.

---

example/demo_survey/src/survey/widgets/home.tsx
packages/evolution-common/src/services/widgets/WidgetConfig.ts
packages/evolution-frontend/src/components/survey/Question.tsx
packages/evolution-frontend/src/components/survey/__tests__/Question.test.tsx
packages/evolution-frontend/src/components/survey/__tests__/__snapshots__/Question.test.tsx.snap
packages/evolution-legacy/src/components/survey/Section.js

Fixes https://github.com/chairemobilite/evolution/issues/146
With the joinPrevious parameter, the previous question will be joined the one in which the option is stated.

Questions: Add a parameter to join questions.

---

example/demo_survey/src/survey/widgets/home.tsx
packages/evolution-frontend/src/components/survey/Question.tsx
packages/evolution-frontend/src/components/survey/__tests__/Question.test.tsx
packages/evolution-frontend/src/components/survey/__tests__/__snapshots__/Question.test.tsx.snap
packages/evolution-legacy/src/components/survey/Section.js
packages/evolution-legacy/src/styles/survey/_question.scss

also update demo survey to join all address fields together, closes #198

use CSS instead of placeholder labels to join fields together

---

packages/evolution-backend/package.json
packages/evolution-common/package.json
packages/evolution-frontend/package.json
packages/evolution-interviewer/package.json

chore: fix yarn format for windows
fixes: #196 
Comments: Can someone check if "yarn format" in evolution also work with Linux or Mac. I could only test with windows. I think, it should work.

chore: fix yarn format for windows

---

locales/en/admin.json
locales/fr/admin.json
packages/evolution-legacy/src/components/admin/Validation.js

Ça pourrait être plus beau, meilleur icon pour le bouton toggle. Je suis ouvert aux suggestions.

Fix #136: bouton pour montrer/cacher liste d'entrevues.

---

packages/evolution-frontend/src/components/pages/auth/AuthPageHOC.tsx
packages/evolution-frontend/src/components/survey/Question.tsx
packages/evolution-legacy/src/components/survey/Button.js
packages/evolution-legacy/src/components/survey/Survey.js

for better accessibility. Note that the enter key is still disabled if the button is not focused with the tab key

allow the use of enter key or space bar when a button is focused

---

packages/evolution-legacy/src/components/survey/Section.js

This needs TESTING because it could have SIDE EFFECTS!

make sure loading state is 0 before focusing on invalid field (fix issue 161)

---

packages/evolution-common/src/services/widgets/WidgetConfig.ts
packages/evolution-frontend/src/actions/utils/WidgetOperation.ts
packages/evolution-interviewer/src/server/routes/interviewer.routes.ts

Otherwise, it clashes with the `/` route for some reason and we get the main application page.

interviewer: Let the apps add the `interviewer` path app.use

---

packages/evolution-frontend/src/components/pageParts/validations/InterviewList.tsx
packages/evolution-frontend/src/components/pageParts/validations/InterviewListComponent.tsx
packages/evolution-legacy/src/components/admin/Validation.js
packages/evolution-legacy/src/components/admin/validation/InterviewSummary.js

Enfin, voici les changements minimaux en un seul commit. Je serai plus prudent avec mes merges!

Fix #136: minimal changes to interview list toggle.

---

packages/evolution-backend/src/models/migrations/20230908204800_createdAtDefaultValue.ts

and participants table. Also update the interview's created_at timestamp to the _startedAt value
fixes #244

db: Update created_at default value to now in interviews

---

packages/evolution-backend/src/config/projectConfig.ts
packages/evolution-backend/src/services/interviews/__tests__/interview.test.ts
packages/evolution-backend/src/services/interviews/interview.ts
packages/evolution-backend/src/services/validations/__tests__/serverValidation.test.ts
packages/evolution-backend/src/services/validations/serverValidation.ts
packages/evolution-frontend/src/components/inputs/InputChoiceSorting.ts

fixes #252
This will allow server validations to depend on other field's values

validations: pass the interview to server validations

---

packages/evolution-frontend/src/components/inputs/InputRadioNumber.tsx
packages/evolution-frontend/src/components/inputs/__tests__/__snapshots__/InputRadioNumber.test.tsx.snap
packages/evolution-frontend/src/components/survey/__tests__/__snapshots__/Question.test.tsx.snap

While fixing issues 2255 and 1090 in od_mtl_2023, I found some other bugs in InputRadioNumber that had to be fixed first.

Improve input radio number

---

package.json

this fix the error when running migrate-test

add project config path to setup-test task

---

packages/evolution-common/src/services/interviews/interview.ts
packages/evolution-common/src/services/widgets/WidgetConfig.ts

and add errorCode optional attribute to InterviewValidation

add _completedAt attribute to InterviewResponses

---

packages/evolution-frontend/src/components/inputs/InputRadio.tsx
packages/evolution-frontend/src/components/inputs/InputRadioNumber.tsx
packages/evolution-frontend/src/components/inputs/InputString.tsx
packages/evolution-frontend/src/components/inputs/__tests__/__snapshots__/InputRadioNumber.test.tsx.snap
packages/evolution-frontend/src/components/survey/__tests__/__snapshots__/Question.test.tsx.snap

Fix 274: make InputRadioNumber re-use radio button code from InputRadio.tsx

---

locales/en/admin.json
locales/fr/admin.json
packages/evolution-backend/src/models/__tests__/interviews.db.test.ts
packages/evolution-backend/src/models/interviews.db.queries.ts
packages/evolution-common/src/services/parsers/ParserFunction.ts
packages/evolution-common/src/services/widgets/PathConfig.ts
packages/evolution-frontend/src/components/pageParts/validations/InterviewByCodeFilter.tsx
packages/evolution-frontend/src/components/pageParts/validations/InterviewListComponent.tsx

validation: Add a filter by access code

---

packages/evolution-legacy/src/components/admin/validation/InterviewStats.js

Collapse title is currently (Personne #1, Personne #2, etc.). Could switch to "Male, 51 ans", etc. if preferable.
Fixes #283.

Fix 283 Add possibility to collapse individual persons.

---

locales/en/admin.json
locales/fr/admin.json
packages/evolution-backend/src/config/projectConfig.ts
packages/evolution-backend/src/models/__tests__/interviews.db.test.ts
packages/evolution-backend/src/models/interviews.db.queries.ts
packages/evolution-frontend/src/components/pageParts/validations/InterviewByCodeFilter.tsx
packages/evolution-frontend/src/components/pageParts/validations/InterviewByDateFilter.tsx
packages/evolution-frontend/src/components/pageParts/validations/InterviewCompletedFilter.tsx
packages/evolution-frontend/src/components/pageParts/validations/InterviewListComponent.tsx
packages/evolution-frontend/src/components/pageParts/validations/ValidationAuditFilter.tsx
packages/evolution-frontend/src/components/pageParts/validations/ValidityColumnFilter.tsx

for some reason, the SQL query `extract(epoch from created_at) = '2023-04-14'` did not work (no results). Had to switch to this solution: https://stackoverflow.com/questions/23335970/postgresql-query-between-date-ranges#comment112830851_48117316
UI:

Interview list filter by date

---

packages/evolution-common/src/services/baseObjects/BaseHousehold.ts
packages/evolution-common/src/services/baseObjects/BaseInterview.ts
packages/evolution-common/src/services/baseObjects/BaseJourney.ts
packages/evolution-common/src/services/baseObjects/BaseOrganization.ts
packages/evolution-common/src/services/baseObjects/BasePerson.ts
packages/evolution-common/src/services/baseObjects/BasePlace.ts
packages/evolution-common/src/services/baseObjects/BaseSegment.ts
packages/evolution-common/src/services/baseObjects/BaseTrip.ts
packages/evolution-common/src/services/baseObjects/BaseTripChain.ts
packages/evolution-common/src/services/baseObjects/BaseVehicle.ts
packages/evolution-common/src/services/baseObjects/BaseVisitedPlace.ts

these attributes should be removed from standard exports

add confidential attributes to base object classes

---

packages/evolution-common/src/services/baseObjects/BaseAddress.ts
packages/evolution-common/src/services/baseObjects/BaseHousehold.ts
packages/evolution-common/src/services/baseObjects/BaseInterview.ts
packages/evolution-common/src/services/baseObjects/BaseJourney.ts
packages/evolution-common/src/services/baseObjects/BaseOrganization.ts
packages/evolution-common/src/services/baseObjects/BasePerson.ts
packages/evolution-common/src/services/baseObjects/BasePlace.ts
packages/evolution-common/src/services/baseObjects/BaseSegment.ts
packages/evolution-common/src/services/baseObjects/BaseTrip.ts
packages/evolution-common/src/services/baseObjects/BaseTripChain.ts
packages/evolution-common/src/services/baseObjects/BaseVehicle.ts
packages/evolution-common/src/services/baseObjects/BaseVisitedPlace.ts
packages/evolution-common/src/services/baseObjects/Sample.ts
packages/evolution-common/src/services/baseObjects/Survey.ts
packages/evolution-common/src/services/baseObjects/Surveyable.ts
packages/evolution-common/src/services/baseObjects/Tripable.ts
packages/evolution-common/src/services/baseObjects/Uuidable.ts
packages/evolution-common/src/services/baseObjects/Validatable.ts
packages/evolution-common/src/services/baseObjects/Vehicleable.ts
packages/evolution-common/src/services/baseObjects/Weight.ts
packages/evolution-common/src/services/baseObjects/WeightMethod.ts
packages/evolution-common/src/services/baseObjects/_template.ts
packages/evolution-common/src/services/baseObjects/attributeTypes/PersonAttributes.ts
packages/evolution-common/src/services/baseObjects/attributeTypes/PlaceAttributes.ts
packages/evolution-frontend/src/components/inputs/InputString.tsx

This is simply syntax changes after running `yarn format`

Run `yarn format` on current code

---

packages/evolution-common/src/services/baseObjects/BasePerson.ts

for some reason it was missing only in this class

add the missing create function to BasePerson

---

packages/evolution-common/src/services/baseObjects/BasePlace.ts
packages/evolution-common/src/services/baseObjects/__tests__/BasePlace.test.ts
packages/evolution-common/src/services/baseObjects/attributeTypes/PlaceAttributes.ts

the lastAction specifies how the geography was geolocated (map clicked, geocoded, marker dragged, etc.)

add lastAction to BasePlace attributes

---

packages/evolution-common/src/services/baseObjects/attributeTypes/PersonAttributes.ts

also update poerson attributes choices to array + type for better usage

add missing choices to BasePerson.occupation

---

packages/evolution-backend/package.json
packages/evolution-common/src/services/baseObjects/BasePlace.ts
packages/evolution-common/src/services/baseObjects/__tests__/BasePlace.test.ts

+ fix version of slugify to fit other packages

add deviceUsed and zoom to BasePlace

---

packages/evolution-common/package.json
packages/evolution-common/src/utils/__tests__/helpers.test.ts
packages/evolution-common/src/utils/helpers.ts

Add helper functions to compare the interview start with the survey start/end dates.
Also add a function to compare the interview start with any date

Add survey dates to config and helper functions to compare

---

.vscode/settings.json

update transition and fix settings.json

update transition and fix settings.json

---

packages/evolution-legacy/src/components/admin/validation/ValidationOnePageSummary.js

this makes it possible to refresh interview after changes during validation

add refreshInterview to InterviewStats component

---

packages/evolution-frontend/src/components/pageParts/validations/InterviewList.tsx
packages/evolution-frontend/src/components/pageParts/validations/InterviewListComponent.tsx

The interview list can be sorted by access code or creation date.

validations: Add sort options to the interview list

---

packages/evolution-generator/src/helpers/createConditionals.tsx

Update import statement in createConditionals.tsx

Update import statement in createConditionals.tsx

---

packages/evolution-generator/src/examples/generatorExampleConfigs.yaml
packages/evolution-generator/src/scripts/generate_sections.py
packages/evolution-generator/src/scripts/generate_survey.py
packages/evolution-generator/src/scripts/generate_widgets.py
packages/evolution-generator/src/scripts/generate_widgets_config.py

Generate widgetsConfig and sections with Generator
We can now generate sections.ts and widgetsConfig.tsx with Generator.

Generate widgetsConfig and sections with Generator

---

packages/evolution-generator/src/helpers/configsHelpers.tsx

Add isSectionComplete in configsHelpers
I need this function for each configs section when I'm using Generator.

Add isSectionComplete in configsHelpers

---

packages/evolution-generator/src/scripts/generate_widgets.py
packages/evolution-generator/src/types/inputTypes.ts

I have been using helpPopup with more input type.

Add more helpPopup for Generator

---

packages/evolution-generator/src/common/defaultInputBase.tsx

The error message is more generic now, and the map is bigger.

Change inputMapFindPlace error message

---

packages/evolution-generator/src/scripts/generate_widgets.py

Sometimes I need to use survey specific validations. We can do it now with customValidations.

Add customValidations with Generator

---

packages/evolution-generator/src/common/defaultInputBase.tsx
packages/evolution-generator/src/scripts/generate_widgets.py

We have to fix this import, so we can use the 'Save and continue' button with the survey using Generator.

Fix validate button action import with Generator

---

packages/evolution-generator/src/scripts/generate_sections.py
packages/evolution-generator/src/types/inputTypes.ts
packages/evolution-generator/src/types/sectionsTypes.ts

- I added types for sections, which will help avoid stupid errors when configuring sections.
- I also added new types for inputs to add widgets that I hadn't yet used with Generator, this will also help us understand the widget.

Add sectionsTypes and new inputTypes

---

packages/evolution-generator/README.md
packages/evolution-generator/src/common/defaultInputBase.tsx
packages/evolution-generator/src/scripts/generate_widgets.py
packages/evolution-generator/src/types/inputTypes.ts

Remove path from InputText of Generator. We don't need path for this input.

Remove path from InfoText of Generator

---

packages/evolution-generator/src/scripts/generate_libelles.py
packages/evolution-generator/src/scripts/generate_widgets.py

Review after #403 
Generate widget names with a group (when there is one).

Generate widget names with group

---

packages/evolution-generator/src/scripts/generate_widgets.py

Remove duplicate generate_widget_name function. 
It seems like I might have made a mistake while performing a 'git rebase'.

Remove duplicate generate_widget_name function

---

packages/evolution-generator/src/scripts/generate_section_configs.py
packages/evolution-generator/src/scripts/generate_sections.py
packages/evolution-generator/src/types/sectionsTypes.ts

fix: #406 
Add groups to sectionConfigs.ts when necessary.
Modify sections.ts with sectionConfigs.ts.
Update sectionsTypes with better types.
Fix previousSection on generate_section_configs.py.

Add groups to sectionConfigs.ts

---

packages/evolution-backend/src/api/survey.validation.routes.ts
packages/evolution-backend/src/models/__tests__/interviews.db.test.ts
packages/evolution-backend/src/models/interviews.db.queries.ts
packages/evolution-backend/src/services/interviews/__tests__/interviews.test.ts
packages/evolution-backend/src/services/interviews/interviews.ts

It is possible to receive an array of strings for filter values. In that case, the result is and AND of those values in the resulting SQL query.

interview filters: Allow an array of values

---

packages/evolution-generator/README.md

fix: #415 
Add document history
Add Start your own survey
Add Generate sections
Update with new information
Fix bug with image

Update Readme of Generator

---

packages/evolution-generator/README.md
packages/evolution-generator/src/scripts/generate_section_configs.py
packages/evolution-generator/src/types/sectionsTypes.ts

fix: #414 
Add template type
Add template to sectionConfigs.ts

Add template to Generator

---

packages/evolution-generator/src/common/defaultInputBase.tsx
packages/evolution-generator/src/types/inputTypes.ts

Note: You can merge without me, it won't conflict with anything.
Add type to InputRadioNumber
Add inputRadioNumberBase

Add type to InputRadioNumber in Generator

---

packages/evolution-generator/src/scripts/generate_section_configs.py

Note: you can merge this one, without my approval. It's just a small fix.
Remove a useless print in Generator

Remove an useless print in Generator

---

packages/evolution-generator/src/scripts/generate_section_configs.py

Change `<` to `<=` so that the last section can be reached.

generator: Fix last section navigation

---

packages/evolution-generator/src/scripts/generate_section_configs.py

Instead of exporting everything

generator: Use the default export for SectionTemplate component

---

packages/evolution-legacy/src/components/survey/Button.js

Use the parseTranslation function to parse the confirm and cancel texts.

widgets: Let Button confirm and cancel texts be `t` functions

---

packages/evolution-backend/src/api/interviews.routes.ts
packages/evolution-backend/src/api/survey.user.routes.ts
packages/evolution-backend/src/api/survey.validation.routes.ts
packages/evolution-backend/src/services/interviews/serverFieldUpdate.ts

fixes #458
This makes it easier to debug individual callbacks when there is error.
Also fix console.error statements to match what they do

serverFieldUpdate: Add field name to error log

---

locales/en/auth.json
locales/fr/auth.json
packages/evolution-common/src/services/audits/types.ts
packages/evolution-common/src/services/baseObjects/BaseInterview.ts
packages/evolution-common/src/services/baseObjects/BaseJourney.ts
packages/evolution-common/src/services/baseObjects/BasePerson.ts
packages/evolution-common/src/services/baseObjects/BasePlace.ts
packages/evolution-common/src/services/baseObjects/BaseTripChain.ts
packages/evolution-common/src/services/baseObjects/BaseVisitedPlace.ts
packages/evolution-frontend/src/actions/Survey.ts
packages/evolution-frontend/src/components/pageParts/validations/InterviewListComponent.tsx
packages/evolution-frontend/src/components/pages/UnauthorizedPage.tsx
packages/evolution-frontend/src/services/errorManagement/errorHandling.ts
packages/evolution-frontend/src/services/interviews/interview.ts
packages/evolution-frontend/src/services/url.ts
packages/evolution-legacy/src/actions/survey/survey.js
packages/evolution-legacy/src/apps/admin/client/index.js
packages/evolution-legacy/src/apps/participant/client/SurveyRouter.js
packages/evolution-legacy/src/apps/participant/client/index.js

* Update Transition
* Add a handler for http codes other than 200 and let redux actions call it with response code
* The handler for unauthorized calls the `verifyAuthentication` function from chaire-lib to properly log the user out if the session has expired.
* Add a custom unauthorized page for Evolution
* Formatting and missing headers

Better handle unauthorized pages to avoid loop

---

packages/evolution-generator/src/scripts/generate_widgets.py

There was a typo between CustomConditional and CustomValidation, so that custom validations were often imported even if not needed.
Custom Conditionals are supported and are expected to be in the `common/customConditionals.ts` file.

generator: Support custom conditionals and fix validations

---

example/demo_survey/tests/test-one-person-no-trips.UI.spec.ts
example/demo_survey/tests/test-survey-UI.spec.ts
example/demo_survey/tests/test-two-adults-no-trips.UI.spec.ts
packages/evolution-frontend/playwright-example.config.ts
packages/evolution-frontend/tests/ui-testing/surveyTestHelpers.ts
packages/evolution-frontend/tests/ui-testing/testHelpers.ts

playwright: Support multiple persons interviews

---

README.md
example/demo_survey/tests/test-one-person-no-trips.UI.spec.ts
example/demo_survey/tests/test-two-adults-no-trips.UI.spec.ts
packages/evolution-frontend/tests/ui-testing/SurveyObjectDetectors.ts
packages/evolution-frontend/tests/ui-testing/surveyTestHelpers.ts
packages/evolution-frontend/tests/ui-testing/testHelpers.ts

* Add tests for datepickers
* Detect trips and segments
* Add counters to generate unique names for test to allow testing multiple times with the same widget/values

playwright: Yet more improvements to UI tests

---

packages/evolution-generator/src/scripts/generate_widgets.py

We don't need common/customWidgets anymore. Let's keep all the section logic inside the sectionName folder. 
Add section path for customWidgets

Add section path for customWidgets

---

packages/evolution-frontend/tests/ui-testing/testHelpers.ts

We need to test inputCheckbox for some of our surveys (MJ, for example).
Add inputCheckboxTest
Format testHelper.ts

Evolution: Add inputCheckboxTest for test UI

---

packages/evolution-generator/src/common/defaultInputBase.tsx
packages/evolution-generator/src/scripts/generate_input_range.py
packages/evolution-generator/src/types/inputTypes.ts

We want to be able to generate InputRange with an input_color depending on the situation easily.
Generate InputRange with input_color

Generate InputRange with input_color

---

packages/evolution-generator/src/scripts/generate_folders.py
packages/evolution-generator/src/scripts/generate_survey.py

I always need to create a section folder when I create a new one, and I get an error for that when I forget to do it. I think it should be done automatically. Let's get the survey production easy.
Generate sections and common folders for Generator.

Add generate_folders script for Generator

---

packages/evolution-generator/src/types/inputTypes.ts

Update inputTypes for Generator

Update inputTypes for Generator

---

packages/evolution-common/src/services/widgets/WidgetConfig.ts
packages/evolution-common/src/utils/helpers.ts
packages/evolution-frontend/src/actions/Survey.ts
packages/evolution-generator/src/common/defaultConditional.tsx
packages/evolution-generator/src/types/inputTypes.ts

It receives an interview as parameter.

Fix type of the StartUpdateInterview callback function

---

packages/evolution-backend/src/models/interviews.db.queries.ts
packages/evolution-backend/src/services/adminExport/exportToCsvByObjectWorkerPool.ts

exports: Add the is_questionable field to interview exports

---

packages/evolution-generator/src/common/validations.tsx

Fix inputRangeValidation validation problems with 'na' value

Generator: Fix inputRangeValidation validation problems with na value

---

packages/evolution-generator/src/types/inputTypes.ts

Note: I should have put it on https://github.com/chairemobilite/evolution/pull/563, but I didn't catch it before the GitHub compilation workflow.
Update inputTypes for InputRange

Generator: Update inputTypes for InputRange

---

packages/evolution-frontend/tests/ui-testing/testHelpers.ts

See individual commits for details
@samuel-duhaime These fixes are required for the Léger redirection UI tests in MJ

playwright: Add query string parameters and nextUrl after start

---

packages/evolution-frontend/tests/ui-testing/surveyTestHelpers.ts
packages/evolution-frontend/tests/ui-testing/testHelpers.ts
packages/evolution-generator/src/scripts/generate_UI_tests.py

Add registerWithEmailTest UI test
Generate start the survey template UI test
Format files

Add registerWithEmailTest UI test

---

example/demo_survey/package.json
example/demo_survey/webpack.admin.config.js
example/demo_survey/webpack.config.js
yarn.lock

They are not useful in the webpacks.

dep: Remove dependencies to bundle-loader and babel-loader

---

packages/evolution-frontend/src/components/inputs/maps/google/InputMapGoogle.tsx

fixes #593
This uses the user's current language for the map language instead of the defaultLocale. It falls back to the default locale if not set.
The map configuration must be fixed throughout the survey, as we cannot call the `useJsApiLoader` a second time with different parameters. The configuration is global and determined only when the first map is shown. After that, changing the language will not change the language of the map, but if the page is refreshed (with F5), it will be updated.
see https://stackoverflow.com/questions/7065420/how-can-i-change-the-language-of-google-maps-on-the-run

map: Use the user's current language when loading the map

---

packages/evolution-generator/src/scripts/generate_choices.py
packages/evolution-generator/src/scripts/generate_widgets.py

I need a custom conditional in choices for the MJ project. 
Add custom conditionals to generate_choices
Comment importation when not necessary in generate_widgets and generate_choices

Evolution: Add custom conditionals to generate_choices in Evolution

---

packages/evolution-legacy/src/styles/survey/_question.scss

This is for fixing issues on MJ: 
https://github.com/chairemobilite/od_mj_2023/issues/275
https://github.com/chairemobilite/od_mj_2023/issues/281
Add space between question and slider
Remove max value and min value
Update cursor
Center current value
Update slider height for something bigger
Space between the slider and the label
Before: 
After:

Fix sliders UI

---

packages/evolution-generator/src/scripts/generate_UI_tests.py

This will make it easier to use the default parameters of this test. 
Generate inputVisibleTest isVisible value to true

Generator: Generate inputVisibleTest isVisible value to true

---

packages/evolution-generator/src/scripts/generate_input_range.py

In MJ, I need to be able to add a label to the middle of the InputRange.
Generate middle label for InputRange

Generator: Generate middle label for InputRange

---

packages/evolution-legacy/src/styles/survey/_question.scss

add font-size to react-picker

---

example/demo_survey/tests/test-input-validation.UI.spec.ts
example/demo_survey/tests/test-one-person-helpers.ts
example/demo_survey/tests/test-one-person-no-trips.UI.spec.ts
packages/evolution-frontend/tests/ui-testing/testHelpers.ts

Write a test for the demo survey that will check input verification for various widgets.
Adds the following tests to the testHelpers file:
Test that input fields will not accept invalid character types Test that invalid string values will highlight the box in red Test that entering an invalid date will autocorrect it Test that clicking the continue button when not all answers are filled will not advance to the next page Test that clicking the continue button when age is under 18 will open a popup

Test: Adds functions for input verification, and test the demo survey

---

packages/evolution-generator/src/scripts/generate_input_range.py

This avoids exception thrown if one of the columns is missing.

generator: Use `get` to get input range labels from dictionary

---

packages/evolution-backend/src/api/survey.validation.routes.ts

use getInterviewByUuid instead of getAllMAtching
this makes the query way faster

change query for interviewSummary

---

packages/evolution-frontend/tests/ui-testing/testHelpers.ts

Adds the leger redirection test to a function in testHelpers that can be called with parameters.
The parameters are the text of the button to click, the url we expect to be redirected to, and the url of the next page
Fix #611

Add leger redirection test helper

---

packages/evolution-frontend/tests/ui-testing/testHelpers.ts

Adds testHelper functions to verify the validation of radio widgets, as well as the textbox that appears when the last option is selected.
Also refactors a few functions to avoid code duplication

Add validation test for radio inputs

---

packages/evolution-frontend/src/components/inputs/InputMapFindPlace.tsx

Fix a display error with InputMapFindPlace

Fix a diplay error with InputMapFindPlace

---

packages/evolution-frontend/tests/ui-testing/testHelpers.ts

fix: #588 
Fetch Google Maps API response with InputMapFindPlaceTest
BREAKING CHANGE: The inputMapFindPlaceTest doesn't need expectMultiple parameters anymore 
The inputMapFindPlaceTest now gets the results directly from the Google Maps API, so it's more consistent 
The inputMapFindPlaceTest will now retry if there are no results 
Yarn format on testHelpers.ts

Fetch Google Maps API response with InputMapFindPlaceTest

---

packages/evolution-frontend/tests/ui-testing/testHelpers.ts

Add switchToFrenchTest

---

packages/evolution-legacy/src/helpers/survey/survey.js

fixes #638
This action goes to the next section if all widgets are valid, but sets the section completed for the current person instead of globally. It should be called by sections' next buttons for sections that are per person.

survey: Add `validateButtonActionWithCompletePerPersonSection` action

---

packages/evolution-generator/src/types/inputTypes.ts

Add defaultZoom type for InputMapFindPlace

---

packages/evolution-backend/src/services/interviews/__tests__/serverFieldUpdate.test.ts
packages/evolution-backend/src/services/interviews/serverFieldUpdate.ts

Add a field to the `ServerFieldUpdateCallback` type to indicate whether to run this callback when the updated value is in the validated_data instead of responses. Defaults to the current behavior of `false`.
When the survey is updated in validation mode via the admin interface, the server field update callbacks will be executed only if explicitly mentioned.

serverFieldUpdate: Run the callbacks on validated_data as well

---

packages/evolution-backend/package.json
packages/evolution-backend/src/api/helpers/downloadCsvFile.ts
packages/evolution-backend/src/models/interviews.db.queries.ts

Download CSV file with the expected responses
Add moment-timezone package in evolution-backend
Update downloadCsvFile to stream
Remove moment-timezone package
Format back interview.db.queries.ts

Download CSV file with the expected responses

---

packages/evolution-backend/src/services/adminExport/exportToCsvByObjectWorkerPool.ts

fixes #694
When a survey attribute is an array of complex types (object), instead of simply joining the values with `|`, we explode the paths to display each of its fields, ie `attribute.0.field1`, `attribute.0.field2`, `attribute.1.field1`, etc.
For arrays of simple type (strings, numbers, etc), the current behavior is kept.

adminExports: explode arrays of object in csv exports

---

.vscode/settings.json
packages/evolution-common/src/config/__tests__/project.config.test.ts
packages/evolution-common/src/config/project.config.ts
packages/evolution-common/src/services/baseObjects/attributeTypes/InterviewParadataAttributes.ts
packages/evolution-common/src/services/baseObjects/interview/Interview.ts
packages/evolution-common/src/services/baseObjects/interview/InterviewAudited.ts
packages/evolution-common/src/services/baseObjects/interview/InterviewParadata.ts
packages/evolution-common/src/services/baseObjects/interview/InterviewParadataUnserializer.ts
packages/evolution-common/src/services/baseObjects/interview/InterviewUnserializer.ts
packages/evolution-common/src/services/interviews/interview.ts
packages/evolution-common/src/services/odSurvey/__tests__/helpers.test.ts
packages/evolution-common/src/services/odSurvey/helpers.ts
packages/evolution-common/src/tests/surveys/testCasesInterview.ts

* Add i18n-ally configuration to support yml locales file
* Add configuration for driving license age
* Add the _isNew property to Segment type
* Add helper functions for person/hh with disabilities
* Run `yarn format` on the current code

Various small commits in preparation for work on the segment section

---

example/demo_survey/src/survey/templates/SegmentsSection.tsx
example/demo_survey/src/survey/templates/VisitedPlacesSection.tsx
packages/evolution-frontend/package.json
packages/evolution-frontend/src/components/hooks/__tests__/useSectionTemplate.test.ts
packages/evolution-frontend/src/components/hooks/useSectionTemplate.ts
packages/evolution-frontend/src/components/pageParts/Section.tsx
packages/evolution-frontend/src/components/pages/Survey.tsx
yarn.lock

This hook contains the common code to preload the section and scroll to the first invalid answer after updating the interview. The `Section`, as well as the `SegmentsSection` and `VisitedPlacesSection` templates use this hook to avoid duplicating the code.

Section: Add a `useSectionTemplate` hook for common section behavior

---

packages/evolution-generator/src/types/sectionsTypes.ts

Update Preload type with SectionPreload type

Update Preload type with SectionPreload type

---

packages/evolution-common/src/services/conditionals/__tests__/checkConditionals.test.ts
packages/evolution-common/src/services/conditionals/checkConditionals.ts
packages/evolution-frontend/src/components/routers/ParticipantSurveyRouter.tsx
packages/evolution-generator/README.md
packages/evolution-generator/package.json
packages/evolution-generator/src/scripts/generate_conditionals.py

Move checkConditionals to evolution-common 
Add tests for checkConditionals
Change checkConditionals to accept conditional like _activePersonId
BREAKING CHANGE: Survey using the Generator need to do 'yarn generateSurvey' again or change the import of the checkConditionals

Generator: Move checkConditional outside the Generator and tests the function.

---

packages/evolution-backend/src/services/adminExport/exportAllToCsvByObject.ts

- convert geometry.coordinates to separate lat and lon columns
- remove quotes from string columns data
- add missing config to unparse toget more compatible csvs
- fix console output to use modulo on 1000s instead of 1001s

Update export by object function

---

packages/evolution-frontend/tests/ui-testing/testHelpers.ts

This is useful for tests where specific cookie values are required.

playwright: add a cookies parameter to initializeTestPage

---

.github/workflows/evolution.yml
Dockerfile

Use node 22 for CI and docker builds by default

Switch builds to Node 22

---

.github/workflows/evolution-generator.yml

It install poetry, install the necessary package and run the generator with the example survey

Add a github workflow that run the generator example

---

packages/evolution-backend/src/services/adminExport/exportAllToCsvByObject.ts

fixes #796
For each section, compute/get the total duration, first start timestamp, number of entries in the section and whether it is completed.
This information replaces the _sections data in the responses to export, as otherwise it only exports the last value, which does not allow to calculate real durations.

admin: modify `_sections` data before exporting data to csv

---

packages/evolution-backend/src/api/helpers/downloadCsvFile.ts

Add excludeFields to downloadCsvFile in admin 
Breaking point: rename requestResponses to requestedFields inside downloadCsvFile

Add excludedFields to downloadCsvFile in admin

---

example/demo_generator/package.json
package.json
packages/evolution-backend/package.json
packages/evolution-common/package.json
packages/evolution-frontend/package.json
packages/evolution-generator/package.json
packages/evolution-interviewer/package.json
packages/evolution-legacy/package.json

fix: #823 
Add yarn format:all and yarn format:python in the package.json

Update format python

---

packages/evolution-generator/src/scripts/generate_UI_tests.py
packages/evolution-generator/src/scripts/generate_folders.py
packages/evolution-generator/src/scripts/generate_questionnaire_list.py
packages/evolution-generator/src/scripts/generate_section_configs.py
packages/evolution-generator/src/scripts/generate_widgets.py
packages/evolution-interviewer/src/server/routes/interviewer.routes.ts

This reformats 5 python files.

Run `yarn format:python` on the code

---

.github/workflows/evolution-generator.yml
.github/workflows/evolution.yml

We add a step check-format in the main ci file to check the typescript format. We add the steps directly in generate-and-build for the python side with the generator test

Check formating in CI

---

packages/evolution-legacy/src/apps/admin/client/index.js
packages/evolution-legacy/src/apps/participant/client/index.js
packages/evolution-legacy/src/styles/survey/styles-admin-survey.scss
packages/evolution-legacy/src/styles/survey/styles-participant-survey.scss
packages/evolution-legacy/src/styles/survey/styles-survey.scss

Note: I tested the admin and the participant with the demo survey. We now only see the admin name.
Separate the CSS for participant and admin

Seperate the CSS for participant and admin

---

packages/evolution-frontend/package.json
yarn.lock

Note: Did I use the good method with my git push? 
```
git remote add sam myUrlRepoName
git push sam v.0.3.0MybranchName
```
Update Playwright version to fix a bug with Google header.
Breaking changes: Update package.json of all survey to this playwright 1.50.0 version.

Breaking Changes: Update Playwright version to fix a bug with Google header.

---

packages/evolution-frontend/package.json
yarn.lock

Cherry-pick from https://github.com/chairemobilite/evolution/pull/838/commits

Cherry-pick: Fix playwright google bug

---

packages/evolution-frontend/src/components/pageParts/SectionNav.tsx
packages/evolution-frontend/src/components/pages/Survey.tsx
packages/evolution-frontend/src/store/loadingState/types.ts
packages/evolution-legacy/src/components/admin/ValidateSurvey.js

And set the loading state as never undefined.

sectionNav: remove unused prop and use hooks when possible

---

packages/evolution-frontend/package.json
yarn.lock

First part of https://github.com/chairemobilite/evolution/issues/887
Update Dompurify package for security
Update dompurify to 3.2.4 or later for security.

Update Dompurify package for security

---

.github/workflows/evolution.yml

Enable the basic workflow for the 0.3.0 branch

Run test on 0.3.0 branch

---

example/demo_survey/package.json
packages/evolution-frontend/package.json
yarn.lock

Update to latest Transition version

Upgrade Transition and react-router package

---

README.md
docs/nomenclature.md

Step 1: update documentation
* Add nomenclature documentation with update progress
* Link to nomenclature documentation in the README file

Nomenclature implementation and renaming 1

---

.github/workflows/evolution.yml
packages/evolution-backend/src/models/__tests__/participants.db.test.ts

Using a postgis database, this executes Evolution's sequential test for every pull request.

ci: add sequential tests to the CI

---

packages/evolution-common/src/services/questionnaire/sections/NavigationService.ts
packages/evolution-common/src/services/questionnaire/sections/navigationHelpers.ts
packages/evolution-generator/src/scripts/generate_section_configs.py

See individual commits for details

Fix demo generator

---

packages/evolution-generator/src/scripts/generate_widgets.py
packages/evolution-generator/src/tests/test_generate_widgets.py

fixes #1083
Extract a function which parses the parameters field as a key, value dictionary, converting all keys to lowercase.
The `get_parameters_values` function now becomes
`get_radio_number_parameters` to prepare to have more widgets support parameters and allow to get specific parameters per widget.
Update tests for case insensitivity

generator: make parameters case-insensitive

---

packages/evolution-generator/src/scripts/generate_widgets.py
packages/evolution-generator/src/tests/test_generate_widgets.py

Generator:  Add customChoices generation in the widgets.
Fix: #1056
Improve widget import logic with smaller function
Enhance tests for import statements and choices generation

Generator:  Add customChoices generation in the widgets.

---

packages/evolution-generator/src/scripts/generate_UI_tests.py

Typo: Fix typo in generate_UI_tests.py

Typo: Fix typo in generate_UI_tests.py

---

.gitignore
packages/evolution-generator/src/scripts/generate_UI_tests.py
packages/evolution-generator/src/scripts/generate_survey.py

Generator: Rename and improve UI tests template
Rename template-tests-UI.ts to common-UI-tests-helpers-template.ts.
Put all sections in a function with some parameters.
Put @link inside the generate UI tests.¸
Generate verifyNavBarButtonStatus test

Generator: Rename and improve UI tests template
